#!/usr/bin/env python3
"""DOM wasm<->JS interop test (WS3-161 / document). Compiles dom_demo.sem to a
.wasm whose dom_* operations are wasm imports, then runs it under node with a
host that backs those imports with a JS-side node map (standing in for the
browser `document`). Asserts the value round-trips: main creates a node, sets it
to 42 via JS, reads it back via JS, and returns 42.

This proves the wasm codegen + the wasm<->JS DOM-interop seam the real
ss_dom_runtime.js browser adapter uses. Exit 0 iff main() == 42.
"""
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SEMANTICSCRIPT = os.path.join(HERE, "semanticscript.py")
SRC = os.path.join(HERE, "dom_demo.sem")
WASM = os.path.join(HERE, "dom_demo.wasm")
RUNNER = os.path.join(HERE, "dom_demo.run.cjs")  # generated by `semanticscript wasm`
HOST = os.path.join(HERE, "_dom_host.cjs")

HOST_JS = r"""
// DOM host: backs the wasm dom_* imports with a JS node map (a stand-in for the
// browser `document`). The wasm calls these to create/set/get a node value.
const fs = require('fs');
const path = require('path');
const nodes = new Map();
let nextId = 1;
const imports = { env: {
  dom_create_node: () => { const id = nextId++; nodes.set(id, 0); return id; },
  dom_set_value: (id, v) => { nodes.set(id, v); return 0; },
  dom_get_value: (id) => nodes.get(id) | 0,
}};
const bytes = fs.readFileSync(path.join(__dirname, 'dom_demo.wasm'));
WebAssembly.instantiate(bytes, imports).then(({ instance }) => {
  const r = instance.exports.main();
  console.log('dom round-trip main() = ' + r + ' (node map size ' + nodes.size + ')');
  process.exit(r === 42 ? 0 : 1);
});
"""


def main():
    node = shutil.which("node")
    if node is None:
        print("SKIP: node not found")
        return 0
    try:
        build = subprocess.run([sys.executable, SEMANTICSCRIPT, "wasm", SRC],
                               capture_output=True, text=True)
        if build.returncode != 0:
            print("FAIL: wasm build: %s" % build.stderr.strip())
            return 1
        with open(HOST, "w", encoding="utf-8") as fh:
            fh.write(HOST_JS)
        run = subprocess.run([node, HOST], capture_output=True, text=True)
        out = (run.stdout or run.stderr or "").strip()
        ok = run.returncode == 0 and "main() = 42" in out
        print("dom: %r -> %s" % (out, "PASS" if ok else "FAIL"))
        return 0 if ok else 1
    finally:
        for f in (WASM, RUNNER, HOST):
            try:
                os.remove(f)
            except OSError:
                pass


if __name__ == "__main__":
    raise SystemExit(main())
