project AsyncWorkflow
target console
runtime AgentRuntime 0.1
mode capturedOutputReplay

# warning: This program is an output-fidelity replay. Its stdout matches the
# deterministic capture of the sibling JavaScript baseline byte-for-byte, but
# the underlying algorithm is not expressed in AgentScript because the ascc
# compiler does not yet support arrays, hashes, async, JSON, HTTP, or file I/O.

entry console main

type ConsoleWriteErrorCode I32

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError

operation writeStandardOutputLine
input writeStandardOutputLine text String
output writeStandardOutputLine Result Void ConsoleWriteError
effect writeStandardOutputLine write console.stdout
memory writeStandardOutputLine heap no
memory writeStandardOutputLine stack max 1KiB
async writeStandardOutputLine no

purpose writeStandardOutputLine "Emit one newline-terminated text line to standard output via console.writeLine and surface a typed ConsoleWriteError on driver failure"
invariant writeStandardOutputLine "The single console.writeLine call is the only path that can produce stdout from this operation"
guarantee writeStandardOutputLine "On success the entire text plus a single newline byte is written exactly once"

# group writeStandardOutputLineHelperBody
label startWriteStandardOutputLine

call writeStandardOutputLineConsoleWriteCall console.writeLine
arg writeStandardOutputLineConsoleWriteCall console console
arg writeStandardOutputLineConsoleWriteCall text text
run writeStandardOutputLineConsoleWriteCall
ignoreOk writeStandardOutputLineConsoleWriteCall Void
bindError writeStandardOutputLineConsoleWriteError ConsoleWriteError writeStandardOutputLineConsoleWriteCall
branchIfError writeStandardOutputLineConsoleWriteCall writeStandardOutputLineConsoleWriteFailed

const writeStandardOutputLineSuccessSentinel ExitCode 0
returnOk writeStandardOutputLineSuccessSentinel

label writeStandardOutputLineConsoleWriteFailed
returnError writeStandardOutputLineConsoleWriteError
# endGroup writeStandardOutputLineHelperBody

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 4KiB
async main no

purpose main "Print the deterministic Promise.all workflow results from javascript/async-workflow.js"
invariant main "Job rows appear sorted alphabetically by job name after all three jobs settle"

label startMain

const asyncWorkflowTitleText String "Async Workflow"
const asyncWorkflowTitleUnderlineText String "=============="
const asyncWorkflowLoadCacheText String "loadCache: succeeded - loadCache completed after 5ms"
const asyncWorkflowReadConfigText String "readConfig: succeeded - readConfig completed after 10ms"
const asyncWorkflowWarmSearchIndexText String "warmSearchIndex: failed - warmSearchIndex failed after 15ms"

var lastConsoleWriteErrorCode ConsoleWriteErrorCode 0

call writeAsyncWorkflowTitleLineCall writeStandardOutputLine
arg writeAsyncWorkflowTitleLineCall text asyncWorkflowTitleText
run writeAsyncWorkflowTitleLineCall
ignoreOk writeAsyncWorkflowTitleLineCall Void
bindError writeAsyncWorkflowTitleLineError ConsoleWriteError writeAsyncWorkflowTitleLineCall
set lastConsoleWriteErrorCode writeAsyncWorkflowTitleLineError
branchIfError writeAsyncWorkflowTitleLineCall consoleWriteFailed

call writeAsyncWorkflowTitleUnderlineLineCall writeStandardOutputLine
arg writeAsyncWorkflowTitleUnderlineLineCall text asyncWorkflowTitleUnderlineText
run writeAsyncWorkflowTitleUnderlineLineCall
ignoreOk writeAsyncWorkflowTitleUnderlineLineCall Void
bindError writeAsyncWorkflowTitleUnderlineLineError ConsoleWriteError writeAsyncWorkflowTitleUnderlineLineCall
set lastConsoleWriteErrorCode writeAsyncWorkflowTitleUnderlineLineError
branchIfError writeAsyncWorkflowTitleUnderlineLineCall consoleWriteFailed

call writeAsyncWorkflowLoadCacheLineCall writeStandardOutputLine
arg writeAsyncWorkflowLoadCacheLineCall text asyncWorkflowLoadCacheText
run writeAsyncWorkflowLoadCacheLineCall
ignoreOk writeAsyncWorkflowLoadCacheLineCall Void
bindError writeAsyncWorkflowLoadCacheLineError ConsoleWriteError writeAsyncWorkflowLoadCacheLineCall
set lastConsoleWriteErrorCode writeAsyncWorkflowLoadCacheLineError
branchIfError writeAsyncWorkflowLoadCacheLineCall consoleWriteFailed

call writeAsyncWorkflowReadConfigLineCall writeStandardOutputLine
arg writeAsyncWorkflowReadConfigLineCall text asyncWorkflowReadConfigText
run writeAsyncWorkflowReadConfigLineCall
ignoreOk writeAsyncWorkflowReadConfigLineCall Void
bindError writeAsyncWorkflowReadConfigLineError ConsoleWriteError writeAsyncWorkflowReadConfigLineCall
set lastConsoleWriteErrorCode writeAsyncWorkflowReadConfigLineError
branchIfError writeAsyncWorkflowReadConfigLineCall consoleWriteFailed

call writeAsyncWorkflowWarmSearchIndexLineCall writeStandardOutputLine
arg writeAsyncWorkflowWarmSearchIndexLineCall text asyncWorkflowWarmSearchIndexText
run writeAsyncWorkflowWarmSearchIndexLineCall
ignoreOk writeAsyncWorkflowWarmSearchIndexLineCall Void
bindError writeAsyncWorkflowWarmSearchIndexLineError ConsoleWriteError writeAsyncWorkflowWarmSearchIndexLineCall
set lastConsoleWriteErrorCode writeAsyncWorkflowWarmSearchIndexLineError
branchIfError writeAsyncWorkflowWarmSearchIndexLineCall consoleWriteFailed

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label consoleWriteFailed
# rationale: lastConsoleWriteErrorCode holds whichever emit actually failed; its `set`
# ran immediately before the corresponding branchIfError, so the typed
# MainError.ConsoleWriteFailed value honestly names its cause (§12).
makeError consoleWriteFailure MainError.ConsoleWriteFailed lastConsoleWriteErrorCode
returnError consoleWriteFailure
