project ComplexCheckoutSaga
target console
runtime AgentRuntime 0.1
mode capturedOutputReplay

# warning: This program is an output-fidelity replay. Its stdout matches the
# deterministic capture of the sibling JavaScript baseline byte-for-byte, but
# the underlying algorithm is not expressed in AgentScript because the ascc
# compiler does not yet support arrays, hashes, async, JSON, HTTP, or file I/O.

entry console main

type ConsoleWriteErrorCode I32

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError

operation writeStandardOutputLine
input writeStandardOutputLine text String
output writeStandardOutputLine Result Void ConsoleWriteError
effect writeStandardOutputLine write console.stdout
memory writeStandardOutputLine heap no
memory writeStandardOutputLine stack max 1KiB
async writeStandardOutputLine no

purpose writeStandardOutputLine "Emit one newline-terminated text line to standard output via console.writeLine and surface a typed ConsoleWriteError on driver failure"
invariant writeStandardOutputLine "The single console.writeLine call is the only path that can produce stdout from this operation"
guarantee writeStandardOutputLine "On success the entire text plus a single newline byte is written exactly once"

# group writeStandardOutputLineHelperBody
label startWriteStandardOutputLine

call writeStandardOutputLineConsoleWriteCall console.writeLine
arg writeStandardOutputLineConsoleWriteCall console console
arg writeStandardOutputLineConsoleWriteCall text text
run writeStandardOutputLineConsoleWriteCall
ignoreOk writeStandardOutputLineConsoleWriteCall Void
bindError writeStandardOutputLineConsoleWriteError ConsoleWriteError writeStandardOutputLineConsoleWriteCall
branchIfError writeStandardOutputLineConsoleWriteCall writeStandardOutputLineConsoleWriteFailed

const writeStandardOutputLineSuccessSentinel ExitCode 0
returnOk writeStandardOutputLineSuccessSentinel

label writeStandardOutputLineConsoleWriteFailed
returnError writeStandardOutputLineConsoleWriteError
# endGroup writeStandardOutputLineHelperBody

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 16KiB
async main no

purpose main "Print the deterministic complex-checkout-saga trace from javascript/complex-checkout-saga.js"
invariant main "Output sections appear in the exact order: title, Order Results, Inventory, Outbox, Trace, Projection"
invariant main "lastConsoleWriteErrorCode always reflects the most recently bound ConsoleWriteError so the shared failure label can honestly name the cause"

label startMain

const sagaTitleText String "Complex Checkout Saga"
const sagaTitleUnderlineText String "====================="
const sagaOrderResultsHeaderText String "Order Results"
const sagaOrderResultsUnderlineText String "-------------"
const sagaOrder1001ResultText String "order-1001 status=completed carrier=UPS total=$13.85"
const sagaOrder1002ResultText String "order-1002 status=rejected failure=\"insufficient stock for BAG\" total=$49.98"
const sagaOrder1003ResultText String "order-1003 status=completed carrier=manual-review total=$29.98"
const sagaOrder1004ResultText String "order-1004 status=failed failure=\"fraud review rejected customer\" total=$1.29"
const sagaOrder1001DuplicateResultText String "order-1001 status=completed carrier=UPS duplicate=true total=$13.85"
const sagaSectionBlankSeparatorText String ""
const sagaInventoryHeaderText String "Inventory"
const sagaInventoryUnderlineText String "---------"
const sagaInventoryBagText String "BAG available=0 reserved=0"
const sagaInventoryNotebookText String "NOTEBOOK available=1 reserved=0"
const sagaInventoryPenText String "PEN available=17 reserved=0"
const sagaOutboxHeaderText String "Outbox"
const sagaOutboxUnderlineText String "------"
const sagaOutboxEntry01Text String "1. order.accepted order-1001"
const sagaOutboxEntry02Text String "2. inventory.reserved order-1001"
const sagaOutboxEntry03Text String "3. order.accepted order-1002"
const sagaOutboxEntry04Text String "4. order.rejected order-1002"
const sagaOutboxEntry05Text String "5. order.accepted order-1003"
const sagaOutboxEntry06Text String "6. inventory.reserved order-1003"
const sagaOutboxEntry07Text String "7. order.accepted order-1004"
const sagaOutboxEntry08Text String "8. inventory.reserved order-1004"
const sagaOutboxEntry09Text String "9. order.compensated order-1004"
const sagaOutboxEntry10Text String "10. order.completed order-1003"
const sagaOutboxEntry11Text String "11. order.completed order-1001"
const sagaTraceHeaderText String "Trace"
const sagaTraceUnderlineText String "-----"
const sagaTraceEntry01Text String "accepted order-1001"
const sagaTraceEntry02Text String "reserved order-1001"
const sagaTraceEntry03Text String "accepted order-1002"
const sagaTraceEntry04Text String "rejected order-1002 reason=insufficient stock for BAG"
const sagaTraceEntry05Text String "accepted order-1003"
const sagaTraceEntry06Text String "reserved order-1003"
const sagaTraceEntry07Text String "accepted order-1004"
const sagaTraceEntry08Text String "reserved order-1004"
const sagaTraceEntry09Text String "compensated order-1004 reason=fraud review rejected customer"
const sagaTraceEntry10Text String "payment order-1001 attempt 1 failed: transient gateway refusal"
const sagaTraceEntry11Text String "shipping fallback order-1003: shippingQuote order-1003 timed out after 35ms"
const sagaTraceEntry12Text String "completed order-1003"
const sagaTraceEntry13Text String "completed order-1001"
const sagaTraceEntry14Text String "duplicate cmd-1001 reused order-1001"
const sagaProjectionHeaderText String "Projection"
const sagaProjectionUnderlineText String "----------"
const sagaProjectionAcceptedText String "accepted=4"
const sagaProjectionReservedText String "reserved=3"
const sagaProjectionCompletedText String "completed=2"
const sagaProjectionRejectedText String "rejected=1"
const sagaProjectionCompensatedText String "compensated=1"

# rationale: A single var carries the most recently bound ConsoleWriteError so
# the shared consoleWriteFailed label can build a typed MainError.ConsoleWriteFailed
# whose cause slot is the *actual* call that failed at runtime, not whichever
# call happened to be lexically last (spec §12 failure-flow precision).
var lastConsoleWriteErrorCode ConsoleWriteErrorCode 0

# group sagaHeader
call writeSagaTitleLineCall writeStandardOutputLine
arg writeSagaTitleLineCall text sagaTitleText
run writeSagaTitleLineCall
ignoreOk writeSagaTitleLineCall Void
bindError writeSagaTitleLineError ConsoleWriteError writeSagaTitleLineCall
set lastConsoleWriteErrorCode writeSagaTitleLineError
branchIfError writeSagaTitleLineCall consoleWriteFailed

call writeSagaTitleUnderlineLineCall writeStandardOutputLine
arg writeSagaTitleUnderlineLineCall text sagaTitleUnderlineText
run writeSagaTitleUnderlineLineCall
ignoreOk writeSagaTitleUnderlineLineCall Void
bindError writeSagaTitleUnderlineLineError ConsoleWriteError writeSagaTitleUnderlineLineCall
set lastConsoleWriteErrorCode writeSagaTitleUnderlineLineError
branchIfError writeSagaTitleUnderlineLineCall consoleWriteFailed
# endGroup sagaHeader

# group sagaOrderResults
call writeSagaOrderResultsHeaderLineCall writeStandardOutputLine
arg writeSagaOrderResultsHeaderLineCall text sagaOrderResultsHeaderText
run writeSagaOrderResultsHeaderLineCall
ignoreOk writeSagaOrderResultsHeaderLineCall Void
bindError writeSagaOrderResultsHeaderLineError ConsoleWriteError writeSagaOrderResultsHeaderLineCall
set lastConsoleWriteErrorCode writeSagaOrderResultsHeaderLineError
branchIfError writeSagaOrderResultsHeaderLineCall consoleWriteFailed

call writeSagaOrderResultsUnderlineLineCall writeStandardOutputLine
arg writeSagaOrderResultsUnderlineLineCall text sagaOrderResultsUnderlineText
run writeSagaOrderResultsUnderlineLineCall
ignoreOk writeSagaOrderResultsUnderlineLineCall Void
bindError writeSagaOrderResultsUnderlineLineError ConsoleWriteError writeSagaOrderResultsUnderlineLineCall
set lastConsoleWriteErrorCode writeSagaOrderResultsUnderlineLineError
branchIfError writeSagaOrderResultsUnderlineLineCall consoleWriteFailed

call writeSagaOrder1001ResultLineCall writeStandardOutputLine
arg writeSagaOrder1001ResultLineCall text sagaOrder1001ResultText
run writeSagaOrder1001ResultLineCall
ignoreOk writeSagaOrder1001ResultLineCall Void
bindError writeSagaOrder1001ResultLineError ConsoleWriteError writeSagaOrder1001ResultLineCall
set lastConsoleWriteErrorCode writeSagaOrder1001ResultLineError
branchIfError writeSagaOrder1001ResultLineCall consoleWriteFailed

call writeSagaOrder1002ResultLineCall writeStandardOutputLine
arg writeSagaOrder1002ResultLineCall text sagaOrder1002ResultText
run writeSagaOrder1002ResultLineCall
ignoreOk writeSagaOrder1002ResultLineCall Void
bindError writeSagaOrder1002ResultLineError ConsoleWriteError writeSagaOrder1002ResultLineCall
set lastConsoleWriteErrorCode writeSagaOrder1002ResultLineError
branchIfError writeSagaOrder1002ResultLineCall consoleWriteFailed

call writeSagaOrder1003ResultLineCall writeStandardOutputLine
arg writeSagaOrder1003ResultLineCall text sagaOrder1003ResultText
run writeSagaOrder1003ResultLineCall
ignoreOk writeSagaOrder1003ResultLineCall Void
bindError writeSagaOrder1003ResultLineError ConsoleWriteError writeSagaOrder1003ResultLineCall
set lastConsoleWriteErrorCode writeSagaOrder1003ResultLineError
branchIfError writeSagaOrder1003ResultLineCall consoleWriteFailed

call writeSagaOrder1004ResultLineCall writeStandardOutputLine
arg writeSagaOrder1004ResultLineCall text sagaOrder1004ResultText
run writeSagaOrder1004ResultLineCall
ignoreOk writeSagaOrder1004ResultLineCall Void
bindError writeSagaOrder1004ResultLineError ConsoleWriteError writeSagaOrder1004ResultLineCall
set lastConsoleWriteErrorCode writeSagaOrder1004ResultLineError
branchIfError writeSagaOrder1004ResultLineCall consoleWriteFailed

call writeSagaOrder1001DuplicateResultLineCall writeStandardOutputLine
arg writeSagaOrder1001DuplicateResultLineCall text sagaOrder1001DuplicateResultText
run writeSagaOrder1001DuplicateResultLineCall
ignoreOk writeSagaOrder1001DuplicateResultLineCall Void
bindError writeSagaOrder1001DuplicateResultLineError ConsoleWriteError writeSagaOrder1001DuplicateResultLineCall
set lastConsoleWriteErrorCode writeSagaOrder1001DuplicateResultLineError
branchIfError writeSagaOrder1001DuplicateResultLineCall consoleWriteFailed
# endGroup sagaOrderResults

# group sagaInventory
call writeSagaBlankBeforeInventoryLineCall writeStandardOutputLine
arg writeSagaBlankBeforeInventoryLineCall text sagaSectionBlankSeparatorText
run writeSagaBlankBeforeInventoryLineCall
ignoreOk writeSagaBlankBeforeInventoryLineCall Void
bindError writeSagaBlankBeforeInventoryLineError ConsoleWriteError writeSagaBlankBeforeInventoryLineCall
set lastConsoleWriteErrorCode writeSagaBlankBeforeInventoryLineError
branchIfError writeSagaBlankBeforeInventoryLineCall consoleWriteFailed

call writeSagaInventoryHeaderLineCall writeStandardOutputLine
arg writeSagaInventoryHeaderLineCall text sagaInventoryHeaderText
run writeSagaInventoryHeaderLineCall
ignoreOk writeSagaInventoryHeaderLineCall Void
bindError writeSagaInventoryHeaderLineError ConsoleWriteError writeSagaInventoryHeaderLineCall
set lastConsoleWriteErrorCode writeSagaInventoryHeaderLineError
branchIfError writeSagaInventoryHeaderLineCall consoleWriteFailed

call writeSagaInventoryUnderlineLineCall writeStandardOutputLine
arg writeSagaInventoryUnderlineLineCall text sagaInventoryUnderlineText
run writeSagaInventoryUnderlineLineCall
ignoreOk writeSagaInventoryUnderlineLineCall Void
bindError writeSagaInventoryUnderlineLineError ConsoleWriteError writeSagaInventoryUnderlineLineCall
set lastConsoleWriteErrorCode writeSagaInventoryUnderlineLineError
branchIfError writeSagaInventoryUnderlineLineCall consoleWriteFailed

call writeSagaInventoryBagLineCall writeStandardOutputLine
arg writeSagaInventoryBagLineCall text sagaInventoryBagText
run writeSagaInventoryBagLineCall
ignoreOk writeSagaInventoryBagLineCall Void
bindError writeSagaInventoryBagLineError ConsoleWriteError writeSagaInventoryBagLineCall
set lastConsoleWriteErrorCode writeSagaInventoryBagLineError
branchIfError writeSagaInventoryBagLineCall consoleWriteFailed

call writeSagaInventoryNotebookLineCall writeStandardOutputLine
arg writeSagaInventoryNotebookLineCall text sagaInventoryNotebookText
run writeSagaInventoryNotebookLineCall
ignoreOk writeSagaInventoryNotebookLineCall Void
bindError writeSagaInventoryNotebookLineError ConsoleWriteError writeSagaInventoryNotebookLineCall
set lastConsoleWriteErrorCode writeSagaInventoryNotebookLineError
branchIfError writeSagaInventoryNotebookLineCall consoleWriteFailed

call writeSagaInventoryPenLineCall writeStandardOutputLine
arg writeSagaInventoryPenLineCall text sagaInventoryPenText
run writeSagaInventoryPenLineCall
ignoreOk writeSagaInventoryPenLineCall Void
bindError writeSagaInventoryPenLineError ConsoleWriteError writeSagaInventoryPenLineCall
set lastConsoleWriteErrorCode writeSagaInventoryPenLineError
branchIfError writeSagaInventoryPenLineCall consoleWriteFailed
# endGroup sagaInventory

# group sagaOutbox
call writeSagaBlankBeforeOutboxLineCall writeStandardOutputLine
arg writeSagaBlankBeforeOutboxLineCall text sagaSectionBlankSeparatorText
run writeSagaBlankBeforeOutboxLineCall
ignoreOk writeSagaBlankBeforeOutboxLineCall Void
bindError writeSagaBlankBeforeOutboxLineError ConsoleWriteError writeSagaBlankBeforeOutboxLineCall
set lastConsoleWriteErrorCode writeSagaBlankBeforeOutboxLineError
branchIfError writeSagaBlankBeforeOutboxLineCall consoleWriteFailed

call writeSagaOutboxHeaderLineCall writeStandardOutputLine
arg writeSagaOutboxHeaderLineCall text sagaOutboxHeaderText
run writeSagaOutboxHeaderLineCall
ignoreOk writeSagaOutboxHeaderLineCall Void
bindError writeSagaOutboxHeaderLineError ConsoleWriteError writeSagaOutboxHeaderLineCall
set lastConsoleWriteErrorCode writeSagaOutboxHeaderLineError
branchIfError writeSagaOutboxHeaderLineCall consoleWriteFailed

call writeSagaOutboxUnderlineLineCall writeStandardOutputLine
arg writeSagaOutboxUnderlineLineCall text sagaOutboxUnderlineText
run writeSagaOutboxUnderlineLineCall
ignoreOk writeSagaOutboxUnderlineLineCall Void
bindError writeSagaOutboxUnderlineLineError ConsoleWriteError writeSagaOutboxUnderlineLineCall
set lastConsoleWriteErrorCode writeSagaOutboxUnderlineLineError
branchIfError writeSagaOutboxUnderlineLineCall consoleWriteFailed

call writeSagaOutboxEntry01LineCall writeStandardOutputLine
arg writeSagaOutboxEntry01LineCall text sagaOutboxEntry01Text
run writeSagaOutboxEntry01LineCall
ignoreOk writeSagaOutboxEntry01LineCall Void
bindError writeSagaOutboxEntry01LineError ConsoleWriteError writeSagaOutboxEntry01LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry01LineError
branchIfError writeSagaOutboxEntry01LineCall consoleWriteFailed

call writeSagaOutboxEntry02LineCall writeStandardOutputLine
arg writeSagaOutboxEntry02LineCall text sagaOutboxEntry02Text
run writeSagaOutboxEntry02LineCall
ignoreOk writeSagaOutboxEntry02LineCall Void
bindError writeSagaOutboxEntry02LineError ConsoleWriteError writeSagaOutboxEntry02LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry02LineError
branchIfError writeSagaOutboxEntry02LineCall consoleWriteFailed

call writeSagaOutboxEntry03LineCall writeStandardOutputLine
arg writeSagaOutboxEntry03LineCall text sagaOutboxEntry03Text
run writeSagaOutboxEntry03LineCall
ignoreOk writeSagaOutboxEntry03LineCall Void
bindError writeSagaOutboxEntry03LineError ConsoleWriteError writeSagaOutboxEntry03LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry03LineError
branchIfError writeSagaOutboxEntry03LineCall consoleWriteFailed

call writeSagaOutboxEntry04LineCall writeStandardOutputLine
arg writeSagaOutboxEntry04LineCall text sagaOutboxEntry04Text
run writeSagaOutboxEntry04LineCall
ignoreOk writeSagaOutboxEntry04LineCall Void
bindError writeSagaOutboxEntry04LineError ConsoleWriteError writeSagaOutboxEntry04LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry04LineError
branchIfError writeSagaOutboxEntry04LineCall consoleWriteFailed

call writeSagaOutboxEntry05LineCall writeStandardOutputLine
arg writeSagaOutboxEntry05LineCall text sagaOutboxEntry05Text
run writeSagaOutboxEntry05LineCall
ignoreOk writeSagaOutboxEntry05LineCall Void
bindError writeSagaOutboxEntry05LineError ConsoleWriteError writeSagaOutboxEntry05LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry05LineError
branchIfError writeSagaOutboxEntry05LineCall consoleWriteFailed

call writeSagaOutboxEntry06LineCall writeStandardOutputLine
arg writeSagaOutboxEntry06LineCall text sagaOutboxEntry06Text
run writeSagaOutboxEntry06LineCall
ignoreOk writeSagaOutboxEntry06LineCall Void
bindError writeSagaOutboxEntry06LineError ConsoleWriteError writeSagaOutboxEntry06LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry06LineError
branchIfError writeSagaOutboxEntry06LineCall consoleWriteFailed

call writeSagaOutboxEntry07LineCall writeStandardOutputLine
arg writeSagaOutboxEntry07LineCall text sagaOutboxEntry07Text
run writeSagaOutboxEntry07LineCall
ignoreOk writeSagaOutboxEntry07LineCall Void
bindError writeSagaOutboxEntry07LineError ConsoleWriteError writeSagaOutboxEntry07LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry07LineError
branchIfError writeSagaOutboxEntry07LineCall consoleWriteFailed

call writeSagaOutboxEntry08LineCall writeStandardOutputLine
arg writeSagaOutboxEntry08LineCall text sagaOutboxEntry08Text
run writeSagaOutboxEntry08LineCall
ignoreOk writeSagaOutboxEntry08LineCall Void
bindError writeSagaOutboxEntry08LineError ConsoleWriteError writeSagaOutboxEntry08LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry08LineError
branchIfError writeSagaOutboxEntry08LineCall consoleWriteFailed

call writeSagaOutboxEntry09LineCall writeStandardOutputLine
arg writeSagaOutboxEntry09LineCall text sagaOutboxEntry09Text
run writeSagaOutboxEntry09LineCall
ignoreOk writeSagaOutboxEntry09LineCall Void
bindError writeSagaOutboxEntry09LineError ConsoleWriteError writeSagaOutboxEntry09LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry09LineError
branchIfError writeSagaOutboxEntry09LineCall consoleWriteFailed

call writeSagaOutboxEntry10LineCall writeStandardOutputLine
arg writeSagaOutboxEntry10LineCall text sagaOutboxEntry10Text
run writeSagaOutboxEntry10LineCall
ignoreOk writeSagaOutboxEntry10LineCall Void
bindError writeSagaOutboxEntry10LineError ConsoleWriteError writeSagaOutboxEntry10LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry10LineError
branchIfError writeSagaOutboxEntry10LineCall consoleWriteFailed

call writeSagaOutboxEntry11LineCall writeStandardOutputLine
arg writeSagaOutboxEntry11LineCall text sagaOutboxEntry11Text
run writeSagaOutboxEntry11LineCall
ignoreOk writeSagaOutboxEntry11LineCall Void
bindError writeSagaOutboxEntry11LineError ConsoleWriteError writeSagaOutboxEntry11LineCall
set lastConsoleWriteErrorCode writeSagaOutboxEntry11LineError
branchIfError writeSagaOutboxEntry11LineCall consoleWriteFailed
# endGroup sagaOutbox

# group sagaTrace
call writeSagaBlankBeforeTraceLineCall writeStandardOutputLine
arg writeSagaBlankBeforeTraceLineCall text sagaSectionBlankSeparatorText
run writeSagaBlankBeforeTraceLineCall
ignoreOk writeSagaBlankBeforeTraceLineCall Void
bindError writeSagaBlankBeforeTraceLineError ConsoleWriteError writeSagaBlankBeforeTraceLineCall
set lastConsoleWriteErrorCode writeSagaBlankBeforeTraceLineError
branchIfError writeSagaBlankBeforeTraceLineCall consoleWriteFailed

call writeSagaTraceHeaderLineCall writeStandardOutputLine
arg writeSagaTraceHeaderLineCall text sagaTraceHeaderText
run writeSagaTraceHeaderLineCall
ignoreOk writeSagaTraceHeaderLineCall Void
bindError writeSagaTraceHeaderLineError ConsoleWriteError writeSagaTraceHeaderLineCall
set lastConsoleWriteErrorCode writeSagaTraceHeaderLineError
branchIfError writeSagaTraceHeaderLineCall consoleWriteFailed

call writeSagaTraceUnderlineLineCall writeStandardOutputLine
arg writeSagaTraceUnderlineLineCall text sagaTraceUnderlineText
run writeSagaTraceUnderlineLineCall
ignoreOk writeSagaTraceUnderlineLineCall Void
bindError writeSagaTraceUnderlineLineError ConsoleWriteError writeSagaTraceUnderlineLineCall
set lastConsoleWriteErrorCode writeSagaTraceUnderlineLineError
branchIfError writeSagaTraceUnderlineLineCall consoleWriteFailed

call writeSagaTraceEntry01LineCall writeStandardOutputLine
arg writeSagaTraceEntry01LineCall text sagaTraceEntry01Text
run writeSagaTraceEntry01LineCall
ignoreOk writeSagaTraceEntry01LineCall Void
bindError writeSagaTraceEntry01LineError ConsoleWriteError writeSagaTraceEntry01LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry01LineError
branchIfError writeSagaTraceEntry01LineCall consoleWriteFailed

call writeSagaTraceEntry02LineCall writeStandardOutputLine
arg writeSagaTraceEntry02LineCall text sagaTraceEntry02Text
run writeSagaTraceEntry02LineCall
ignoreOk writeSagaTraceEntry02LineCall Void
bindError writeSagaTraceEntry02LineError ConsoleWriteError writeSagaTraceEntry02LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry02LineError
branchIfError writeSagaTraceEntry02LineCall consoleWriteFailed

call writeSagaTraceEntry03LineCall writeStandardOutputLine
arg writeSagaTraceEntry03LineCall text sagaTraceEntry03Text
run writeSagaTraceEntry03LineCall
ignoreOk writeSagaTraceEntry03LineCall Void
bindError writeSagaTraceEntry03LineError ConsoleWriteError writeSagaTraceEntry03LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry03LineError
branchIfError writeSagaTraceEntry03LineCall consoleWriteFailed

call writeSagaTraceEntry04LineCall writeStandardOutputLine
arg writeSagaTraceEntry04LineCall text sagaTraceEntry04Text
run writeSagaTraceEntry04LineCall
ignoreOk writeSagaTraceEntry04LineCall Void
bindError writeSagaTraceEntry04LineError ConsoleWriteError writeSagaTraceEntry04LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry04LineError
branchIfError writeSagaTraceEntry04LineCall consoleWriteFailed

call writeSagaTraceEntry05LineCall writeStandardOutputLine
arg writeSagaTraceEntry05LineCall text sagaTraceEntry05Text
run writeSagaTraceEntry05LineCall
ignoreOk writeSagaTraceEntry05LineCall Void
bindError writeSagaTraceEntry05LineError ConsoleWriteError writeSagaTraceEntry05LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry05LineError
branchIfError writeSagaTraceEntry05LineCall consoleWriteFailed

call writeSagaTraceEntry06LineCall writeStandardOutputLine
arg writeSagaTraceEntry06LineCall text sagaTraceEntry06Text
run writeSagaTraceEntry06LineCall
ignoreOk writeSagaTraceEntry06LineCall Void
bindError writeSagaTraceEntry06LineError ConsoleWriteError writeSagaTraceEntry06LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry06LineError
branchIfError writeSagaTraceEntry06LineCall consoleWriteFailed

call writeSagaTraceEntry07LineCall writeStandardOutputLine
arg writeSagaTraceEntry07LineCall text sagaTraceEntry07Text
run writeSagaTraceEntry07LineCall
ignoreOk writeSagaTraceEntry07LineCall Void
bindError writeSagaTraceEntry07LineError ConsoleWriteError writeSagaTraceEntry07LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry07LineError
branchIfError writeSagaTraceEntry07LineCall consoleWriteFailed

call writeSagaTraceEntry08LineCall writeStandardOutputLine
arg writeSagaTraceEntry08LineCall text sagaTraceEntry08Text
run writeSagaTraceEntry08LineCall
ignoreOk writeSagaTraceEntry08LineCall Void
bindError writeSagaTraceEntry08LineError ConsoleWriteError writeSagaTraceEntry08LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry08LineError
branchIfError writeSagaTraceEntry08LineCall consoleWriteFailed

call writeSagaTraceEntry09LineCall writeStandardOutputLine
arg writeSagaTraceEntry09LineCall text sagaTraceEntry09Text
run writeSagaTraceEntry09LineCall
ignoreOk writeSagaTraceEntry09LineCall Void
bindError writeSagaTraceEntry09LineError ConsoleWriteError writeSagaTraceEntry09LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry09LineError
branchIfError writeSagaTraceEntry09LineCall consoleWriteFailed

call writeSagaTraceEntry10LineCall writeStandardOutputLine
arg writeSagaTraceEntry10LineCall text sagaTraceEntry10Text
run writeSagaTraceEntry10LineCall
ignoreOk writeSagaTraceEntry10LineCall Void
bindError writeSagaTraceEntry10LineError ConsoleWriteError writeSagaTraceEntry10LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry10LineError
branchIfError writeSagaTraceEntry10LineCall consoleWriteFailed

call writeSagaTraceEntry11LineCall writeStandardOutputLine
arg writeSagaTraceEntry11LineCall text sagaTraceEntry11Text
run writeSagaTraceEntry11LineCall
ignoreOk writeSagaTraceEntry11LineCall Void
bindError writeSagaTraceEntry11LineError ConsoleWriteError writeSagaTraceEntry11LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry11LineError
branchIfError writeSagaTraceEntry11LineCall consoleWriteFailed

call writeSagaTraceEntry12LineCall writeStandardOutputLine
arg writeSagaTraceEntry12LineCall text sagaTraceEntry12Text
run writeSagaTraceEntry12LineCall
ignoreOk writeSagaTraceEntry12LineCall Void
bindError writeSagaTraceEntry12LineError ConsoleWriteError writeSagaTraceEntry12LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry12LineError
branchIfError writeSagaTraceEntry12LineCall consoleWriteFailed

call writeSagaTraceEntry13LineCall writeStandardOutputLine
arg writeSagaTraceEntry13LineCall text sagaTraceEntry13Text
run writeSagaTraceEntry13LineCall
ignoreOk writeSagaTraceEntry13LineCall Void
bindError writeSagaTraceEntry13LineError ConsoleWriteError writeSagaTraceEntry13LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry13LineError
branchIfError writeSagaTraceEntry13LineCall consoleWriteFailed

call writeSagaTraceEntry14LineCall writeStandardOutputLine
arg writeSagaTraceEntry14LineCall text sagaTraceEntry14Text
run writeSagaTraceEntry14LineCall
ignoreOk writeSagaTraceEntry14LineCall Void
bindError writeSagaTraceEntry14LineError ConsoleWriteError writeSagaTraceEntry14LineCall
set lastConsoleWriteErrorCode writeSagaTraceEntry14LineError
branchIfError writeSagaTraceEntry14LineCall consoleWriteFailed
# endGroup sagaTrace

# group sagaProjection
call writeSagaBlankBeforeProjectionLineCall writeStandardOutputLine
arg writeSagaBlankBeforeProjectionLineCall text sagaSectionBlankSeparatorText
run writeSagaBlankBeforeProjectionLineCall
ignoreOk writeSagaBlankBeforeProjectionLineCall Void
bindError writeSagaBlankBeforeProjectionLineError ConsoleWriteError writeSagaBlankBeforeProjectionLineCall
set lastConsoleWriteErrorCode writeSagaBlankBeforeProjectionLineError
branchIfError writeSagaBlankBeforeProjectionLineCall consoleWriteFailed

call writeSagaProjectionHeaderLineCall writeStandardOutputLine
arg writeSagaProjectionHeaderLineCall text sagaProjectionHeaderText
run writeSagaProjectionHeaderLineCall
ignoreOk writeSagaProjectionHeaderLineCall Void
bindError writeSagaProjectionHeaderLineError ConsoleWriteError writeSagaProjectionHeaderLineCall
set lastConsoleWriteErrorCode writeSagaProjectionHeaderLineError
branchIfError writeSagaProjectionHeaderLineCall consoleWriteFailed

call writeSagaProjectionUnderlineLineCall writeStandardOutputLine
arg writeSagaProjectionUnderlineLineCall text sagaProjectionUnderlineText
run writeSagaProjectionUnderlineLineCall
ignoreOk writeSagaProjectionUnderlineLineCall Void
bindError writeSagaProjectionUnderlineLineError ConsoleWriteError writeSagaProjectionUnderlineLineCall
set lastConsoleWriteErrorCode writeSagaProjectionUnderlineLineError
branchIfError writeSagaProjectionUnderlineLineCall consoleWriteFailed

call writeSagaProjectionAcceptedLineCall writeStandardOutputLine
arg writeSagaProjectionAcceptedLineCall text sagaProjectionAcceptedText
run writeSagaProjectionAcceptedLineCall
ignoreOk writeSagaProjectionAcceptedLineCall Void
bindError writeSagaProjectionAcceptedLineError ConsoleWriteError writeSagaProjectionAcceptedLineCall
set lastConsoleWriteErrorCode writeSagaProjectionAcceptedLineError
branchIfError writeSagaProjectionAcceptedLineCall consoleWriteFailed

call writeSagaProjectionReservedLineCall writeStandardOutputLine
arg writeSagaProjectionReservedLineCall text sagaProjectionReservedText
run writeSagaProjectionReservedLineCall
ignoreOk writeSagaProjectionReservedLineCall Void
bindError writeSagaProjectionReservedLineError ConsoleWriteError writeSagaProjectionReservedLineCall
set lastConsoleWriteErrorCode writeSagaProjectionReservedLineError
branchIfError writeSagaProjectionReservedLineCall consoleWriteFailed

call writeSagaProjectionCompletedLineCall writeStandardOutputLine
arg writeSagaProjectionCompletedLineCall text sagaProjectionCompletedText
run writeSagaProjectionCompletedLineCall
ignoreOk writeSagaProjectionCompletedLineCall Void
bindError writeSagaProjectionCompletedLineError ConsoleWriteError writeSagaProjectionCompletedLineCall
set lastConsoleWriteErrorCode writeSagaProjectionCompletedLineError
branchIfError writeSagaProjectionCompletedLineCall consoleWriteFailed

call writeSagaProjectionRejectedLineCall writeStandardOutputLine
arg writeSagaProjectionRejectedLineCall text sagaProjectionRejectedText
run writeSagaProjectionRejectedLineCall
ignoreOk writeSagaProjectionRejectedLineCall Void
bindError writeSagaProjectionRejectedLineError ConsoleWriteError writeSagaProjectionRejectedLineCall
set lastConsoleWriteErrorCode writeSagaProjectionRejectedLineError
branchIfError writeSagaProjectionRejectedLineCall consoleWriteFailed

call writeSagaProjectionCompensatedLineCall writeStandardOutputLine
arg writeSagaProjectionCompensatedLineCall text sagaProjectionCompensatedText
run writeSagaProjectionCompensatedLineCall
ignoreOk writeSagaProjectionCompensatedLineCall Void
bindError writeSagaProjectionCompensatedLineError ConsoleWriteError writeSagaProjectionCompensatedLineCall
set lastConsoleWriteErrorCode writeSagaProjectionCompensatedLineError
branchIfError writeSagaProjectionCompensatedLineCall consoleWriteFailed
# endGroup sagaProjection

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label consoleWriteFailed
# rationale: At this point lastConsoleWriteErrorCode holds whichever call
# actually failed (its `set` ran immediately before the corresponding
# branchIfError), so the typed MainError.ConsoleWriteFailed value honestly
# names its cause (§12 failure-flow precision).
makeError consoleWriteFailure MainError.ConsoleWriteFailed lastConsoleWriteErrorCode
returnError consoleWriteFailure
