project CounterintuitiveCoercion
target console
runtime AgentRuntime 0.1
mode capturedOutputReplay

# warning: This program is an output-fidelity replay. Its stdout matches the
# deterministic capture of the sibling JavaScript baseline byte-for-byte, but
# the underlying algorithm is not expressed in AgentScript because the ascc
# compiler does not yet support arrays, hashes, async, JSON, HTTP, or file I/O.

entry console main

type ConsoleWriteErrorCode I32

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError

operation writeStandardOutputLine
input writeStandardOutputLine text String
output writeStandardOutputLine Result Void ConsoleWriteError
effect writeStandardOutputLine write console.stdout
memory writeStandardOutputLine heap no
memory writeStandardOutputLine stack max 1KiB
async writeStandardOutputLine no

purpose writeStandardOutputLine "Emit one newline-terminated text line to standard output via console.writeLine and surface a typed ConsoleWriteError on driver failure"
invariant writeStandardOutputLine "The single console.writeLine call is the only path that can produce stdout from this operation"
guarantee writeStandardOutputLine "On success the entire text plus a single newline byte is written exactly once"

# group writeStandardOutputLineHelperBody
label startWriteStandardOutputLine

call writeStandardOutputLineConsoleWriteCall console.writeLine
arg writeStandardOutputLineConsoleWriteCall console console
arg writeStandardOutputLineConsoleWriteCall text text
run writeStandardOutputLineConsoleWriteCall
ignoreOk writeStandardOutputLineConsoleWriteCall Void
bindError writeStandardOutputLineConsoleWriteError ConsoleWriteError writeStandardOutputLineConsoleWriteCall
branchIfError writeStandardOutputLineConsoleWriteCall writeStandardOutputLineConsoleWriteFailed

const writeStandardOutputLineSuccessSentinel ExitCode 0
returnOk writeStandardOutputLineSuccessSentinel

label writeStandardOutputLineConsoleWriteFailed
returnError writeStandardOutputLineConsoleWriteError
# endGroup writeStandardOutputLineHelperBody

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 4KiB
async main no

purpose main "Print the JavaScript loose-equality demonstration output from javascript/counterintuitive-coercion.js"
invariant main "Each result line is followed by its explanation line, in source order"

label startMain

const coercionTitleText String "Counterintuitive Coercion"
const coercionTitleUnderlineText String "========================="
const coercionArrayEqFalseText String "[] == false => true"
const coercionArrayEqFalseExplanationText String "  [] becomes an empty string, then 0; false also becomes 0."
const coercionArrayEqNotArrayText String "[] == ![] => true"
const coercionArrayEqNotArrayExplanationText String "  ![] is false, then the comparison follows the [] == false path."
const coercionEmptyStringEqZeroText String "\"\" == 0 => true"
const coercionEmptyStringEqZeroExplanationText String "  The empty string becomes numeric 0."
const coercionStringZeroEqFalseText String "\"0\" == false => true"
const coercionStringZeroEqFalseExplanationText String "  Both sides become numeric 0."
const coercionNullEqUndefinedText String "null == undefined => true"
const coercionNullEqUndefinedExplanationText String "  Loose equality has a special case for null and undefined."
const coercionNullEqZeroText String "null == 0 => false"
const coercionNullEqZeroExplanationText String "  The null/undefined special case does not extend to numbers."
const coercionBooleanStringFalseText String "Boolean(\"false\") => true"
const coercionBooleanStringFalseExplanationText String "  Any non-empty string is truthy."

var lastConsoleWriteErrorCode ConsoleWriteErrorCode 0

call writeCoercionTitleLineCall writeStandardOutputLine
arg writeCoercionTitleLineCall text coercionTitleText
run writeCoercionTitleLineCall
ignoreOk writeCoercionTitleLineCall Void
bindError writeCoercionTitleLineError ConsoleWriteError writeCoercionTitleLineCall
set lastConsoleWriteErrorCode writeCoercionTitleLineError
branchIfError writeCoercionTitleLineCall consoleWriteFailed

call writeCoercionTitleUnderlineLineCall writeStandardOutputLine
arg writeCoercionTitleUnderlineLineCall text coercionTitleUnderlineText
run writeCoercionTitleUnderlineLineCall
ignoreOk writeCoercionTitleUnderlineLineCall Void
bindError writeCoercionTitleUnderlineLineError ConsoleWriteError writeCoercionTitleUnderlineLineCall
set lastConsoleWriteErrorCode writeCoercionTitleUnderlineLineError
branchIfError writeCoercionTitleUnderlineLineCall consoleWriteFailed

call writeCoercionArrayEqFalseLineCall writeStandardOutputLine
arg writeCoercionArrayEqFalseLineCall text coercionArrayEqFalseText
run writeCoercionArrayEqFalseLineCall
ignoreOk writeCoercionArrayEqFalseLineCall Void
bindError writeCoercionArrayEqFalseLineError ConsoleWriteError writeCoercionArrayEqFalseLineCall
set lastConsoleWriteErrorCode writeCoercionArrayEqFalseLineError
branchIfError writeCoercionArrayEqFalseLineCall consoleWriteFailed

call writeCoercionArrayEqFalseExplanationLineCall writeStandardOutputLine
arg writeCoercionArrayEqFalseExplanationLineCall text coercionArrayEqFalseExplanationText
run writeCoercionArrayEqFalseExplanationLineCall
ignoreOk writeCoercionArrayEqFalseExplanationLineCall Void
bindError writeCoercionArrayEqFalseExplanationLineError ConsoleWriteError writeCoercionArrayEqFalseExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionArrayEqFalseExplanationLineError
branchIfError writeCoercionArrayEqFalseExplanationLineCall consoleWriteFailed

call writeCoercionArrayEqNotArrayLineCall writeStandardOutputLine
arg writeCoercionArrayEqNotArrayLineCall text coercionArrayEqNotArrayText
run writeCoercionArrayEqNotArrayLineCall
ignoreOk writeCoercionArrayEqNotArrayLineCall Void
bindError writeCoercionArrayEqNotArrayLineError ConsoleWriteError writeCoercionArrayEqNotArrayLineCall
set lastConsoleWriteErrorCode writeCoercionArrayEqNotArrayLineError
branchIfError writeCoercionArrayEqNotArrayLineCall consoleWriteFailed

call writeCoercionArrayEqNotArrayExplanationLineCall writeStandardOutputLine
arg writeCoercionArrayEqNotArrayExplanationLineCall text coercionArrayEqNotArrayExplanationText
run writeCoercionArrayEqNotArrayExplanationLineCall
ignoreOk writeCoercionArrayEqNotArrayExplanationLineCall Void
bindError writeCoercionArrayEqNotArrayExplanationLineError ConsoleWriteError writeCoercionArrayEqNotArrayExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionArrayEqNotArrayExplanationLineError
branchIfError writeCoercionArrayEqNotArrayExplanationLineCall consoleWriteFailed

call writeCoercionEmptyStringEqZeroLineCall writeStandardOutputLine
arg writeCoercionEmptyStringEqZeroLineCall text coercionEmptyStringEqZeroText
run writeCoercionEmptyStringEqZeroLineCall
ignoreOk writeCoercionEmptyStringEqZeroLineCall Void
bindError writeCoercionEmptyStringEqZeroLineError ConsoleWriteError writeCoercionEmptyStringEqZeroLineCall
set lastConsoleWriteErrorCode writeCoercionEmptyStringEqZeroLineError
branchIfError writeCoercionEmptyStringEqZeroLineCall consoleWriteFailed

call writeCoercionEmptyStringEqZeroExplanationLineCall writeStandardOutputLine
arg writeCoercionEmptyStringEqZeroExplanationLineCall text coercionEmptyStringEqZeroExplanationText
run writeCoercionEmptyStringEqZeroExplanationLineCall
ignoreOk writeCoercionEmptyStringEqZeroExplanationLineCall Void
bindError writeCoercionEmptyStringEqZeroExplanationLineError ConsoleWriteError writeCoercionEmptyStringEqZeroExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionEmptyStringEqZeroExplanationLineError
branchIfError writeCoercionEmptyStringEqZeroExplanationLineCall consoleWriteFailed

call writeCoercionStringZeroEqFalseLineCall writeStandardOutputLine
arg writeCoercionStringZeroEqFalseLineCall text coercionStringZeroEqFalseText
run writeCoercionStringZeroEqFalseLineCall
ignoreOk writeCoercionStringZeroEqFalseLineCall Void
bindError writeCoercionStringZeroEqFalseLineError ConsoleWriteError writeCoercionStringZeroEqFalseLineCall
set lastConsoleWriteErrorCode writeCoercionStringZeroEqFalseLineError
branchIfError writeCoercionStringZeroEqFalseLineCall consoleWriteFailed

call writeCoercionStringZeroEqFalseExplanationLineCall writeStandardOutputLine
arg writeCoercionStringZeroEqFalseExplanationLineCall text coercionStringZeroEqFalseExplanationText
run writeCoercionStringZeroEqFalseExplanationLineCall
ignoreOk writeCoercionStringZeroEqFalseExplanationLineCall Void
bindError writeCoercionStringZeroEqFalseExplanationLineError ConsoleWriteError writeCoercionStringZeroEqFalseExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionStringZeroEqFalseExplanationLineError
branchIfError writeCoercionStringZeroEqFalseExplanationLineCall consoleWriteFailed

call writeCoercionNullEqUndefinedLineCall writeStandardOutputLine
arg writeCoercionNullEqUndefinedLineCall text coercionNullEqUndefinedText
run writeCoercionNullEqUndefinedLineCall
ignoreOk writeCoercionNullEqUndefinedLineCall Void
bindError writeCoercionNullEqUndefinedLineError ConsoleWriteError writeCoercionNullEqUndefinedLineCall
set lastConsoleWriteErrorCode writeCoercionNullEqUndefinedLineError
branchIfError writeCoercionNullEqUndefinedLineCall consoleWriteFailed

call writeCoercionNullEqUndefinedExplanationLineCall writeStandardOutputLine
arg writeCoercionNullEqUndefinedExplanationLineCall text coercionNullEqUndefinedExplanationText
run writeCoercionNullEqUndefinedExplanationLineCall
ignoreOk writeCoercionNullEqUndefinedExplanationLineCall Void
bindError writeCoercionNullEqUndefinedExplanationLineError ConsoleWriteError writeCoercionNullEqUndefinedExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionNullEqUndefinedExplanationLineError
branchIfError writeCoercionNullEqUndefinedExplanationLineCall consoleWriteFailed

call writeCoercionNullEqZeroLineCall writeStandardOutputLine
arg writeCoercionNullEqZeroLineCall text coercionNullEqZeroText
run writeCoercionNullEqZeroLineCall
ignoreOk writeCoercionNullEqZeroLineCall Void
bindError writeCoercionNullEqZeroLineError ConsoleWriteError writeCoercionNullEqZeroLineCall
set lastConsoleWriteErrorCode writeCoercionNullEqZeroLineError
branchIfError writeCoercionNullEqZeroLineCall consoleWriteFailed

call writeCoercionNullEqZeroExplanationLineCall writeStandardOutputLine
arg writeCoercionNullEqZeroExplanationLineCall text coercionNullEqZeroExplanationText
run writeCoercionNullEqZeroExplanationLineCall
ignoreOk writeCoercionNullEqZeroExplanationLineCall Void
bindError writeCoercionNullEqZeroExplanationLineError ConsoleWriteError writeCoercionNullEqZeroExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionNullEqZeroExplanationLineError
branchIfError writeCoercionNullEqZeroExplanationLineCall consoleWriteFailed

call writeCoercionBooleanStringFalseLineCall writeStandardOutputLine
arg writeCoercionBooleanStringFalseLineCall text coercionBooleanStringFalseText
run writeCoercionBooleanStringFalseLineCall
ignoreOk writeCoercionBooleanStringFalseLineCall Void
bindError writeCoercionBooleanStringFalseLineError ConsoleWriteError writeCoercionBooleanStringFalseLineCall
set lastConsoleWriteErrorCode writeCoercionBooleanStringFalseLineError
branchIfError writeCoercionBooleanStringFalseLineCall consoleWriteFailed

call writeCoercionBooleanStringFalseExplanationLineCall writeStandardOutputLine
arg writeCoercionBooleanStringFalseExplanationLineCall text coercionBooleanStringFalseExplanationText
run writeCoercionBooleanStringFalseExplanationLineCall
ignoreOk writeCoercionBooleanStringFalseExplanationLineCall Void
bindError writeCoercionBooleanStringFalseExplanationLineError ConsoleWriteError writeCoercionBooleanStringFalseExplanationLineCall
set lastConsoleWriteErrorCode writeCoercionBooleanStringFalseExplanationLineError
branchIfError writeCoercionBooleanStringFalseExplanationLineCall consoleWriteFailed

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label consoleWriteFailed
# rationale: lastConsoleWriteErrorCode holds whichever emit actually failed; its `set`
# ran immediately before the corresponding branchIfError, so the typed
# MainError.ConsoleWriteFailed value honestly names its cause (§12).
makeError consoleWriteFailure MainError.ConsoleWriteFailed lastConsoleWriteErrorCode
returnError consoleWriteFailure
