project EventWorkflow
target console
runtime AgentRuntime 0.1
mode capturedOutputReplay

# warning: This program is an output-fidelity replay. Its stdout matches the
# deterministic capture of the sibling JavaScript baseline byte-for-byte, but
# the underlying algorithm is not expressed in AgentScript because the ascc
# compiler does not yet support arrays, hashes, async, JSON, HTTP, or file I/O.

entry console main

type ConsoleWriteErrorCode I32

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError

operation writeStandardOutputLine
input writeStandardOutputLine text String
output writeStandardOutputLine Result Void ConsoleWriteError
effect writeStandardOutputLine write console.stdout
memory writeStandardOutputLine heap no
memory writeStandardOutputLine stack max 1KiB
async writeStandardOutputLine no

purpose writeStandardOutputLine "Emit one newline-terminated text line to standard output via console.writeLine and surface a typed ConsoleWriteError on driver failure"
invariant writeStandardOutputLine "The single console.writeLine call is the only path that can produce stdout from this operation"
guarantee writeStandardOutputLine "On success the entire text plus a single newline byte is written exactly once"

# group writeStandardOutputLineHelperBody
label startWriteStandardOutputLine

call writeStandardOutputLineConsoleWriteCall console.writeLine
arg writeStandardOutputLineConsoleWriteCall console console
arg writeStandardOutputLineConsoleWriteCall text text
run writeStandardOutputLineConsoleWriteCall
ignoreOk writeStandardOutputLineConsoleWriteCall Void
bindError writeStandardOutputLineConsoleWriteError ConsoleWriteError writeStandardOutputLineConsoleWriteCall
branchIfError writeStandardOutputLineConsoleWriteCall writeStandardOutputLineConsoleWriteFailed

const writeStandardOutputLineSuccessSentinel ExitCode 0
returnOk writeStandardOutputLineSuccessSentinel

label writeStandardOutputLineConsoleWriteFailed
returnError writeStandardOutputLineConsoleWriteError
# endGroup writeStandardOutputLineHelperBody

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 4KiB
async main no

purpose main "Print the deterministic event-workflow trace from javascript/event-workflow.js"
invariant main "Trace lines appear in emit order: created, paid, shipped for order-2001"

label startMain

const eventWorkflowTitleText String "Event Workflow"
const eventWorkflowTitleUnderlineText String "=============="
const eventWorkflowCreatedText String "created order-2001 for Katherine"
const eventWorkflowPaidText String "paid order-2001 amount=3499"
const eventWorkflowShippedText String "shipped order-2001 carrier=UPS"

var lastConsoleWriteErrorCode ConsoleWriteErrorCode 0

call writeEventWorkflowTitleLineCall writeStandardOutputLine
arg writeEventWorkflowTitleLineCall text eventWorkflowTitleText
run writeEventWorkflowTitleLineCall
ignoreOk writeEventWorkflowTitleLineCall Void
bindError writeEventWorkflowTitleLineError ConsoleWriteError writeEventWorkflowTitleLineCall
set lastConsoleWriteErrorCode writeEventWorkflowTitleLineError
branchIfError writeEventWorkflowTitleLineCall consoleWriteFailed

call writeEventWorkflowTitleUnderlineLineCall writeStandardOutputLine
arg writeEventWorkflowTitleUnderlineLineCall text eventWorkflowTitleUnderlineText
run writeEventWorkflowTitleUnderlineLineCall
ignoreOk writeEventWorkflowTitleUnderlineLineCall Void
bindError writeEventWorkflowTitleUnderlineLineError ConsoleWriteError writeEventWorkflowTitleUnderlineLineCall
set lastConsoleWriteErrorCode writeEventWorkflowTitleUnderlineLineError
branchIfError writeEventWorkflowTitleUnderlineLineCall consoleWriteFailed

call writeEventWorkflowCreatedLineCall writeStandardOutputLine
arg writeEventWorkflowCreatedLineCall text eventWorkflowCreatedText
run writeEventWorkflowCreatedLineCall
ignoreOk writeEventWorkflowCreatedLineCall Void
bindError writeEventWorkflowCreatedLineError ConsoleWriteError writeEventWorkflowCreatedLineCall
set lastConsoleWriteErrorCode writeEventWorkflowCreatedLineError
branchIfError writeEventWorkflowCreatedLineCall consoleWriteFailed

call writeEventWorkflowPaidLineCall writeStandardOutputLine
arg writeEventWorkflowPaidLineCall text eventWorkflowPaidText
run writeEventWorkflowPaidLineCall
ignoreOk writeEventWorkflowPaidLineCall Void
bindError writeEventWorkflowPaidLineError ConsoleWriteError writeEventWorkflowPaidLineCall
set lastConsoleWriteErrorCode writeEventWorkflowPaidLineError
branchIfError writeEventWorkflowPaidLineCall consoleWriteFailed

call writeEventWorkflowShippedLineCall writeStandardOutputLine
arg writeEventWorkflowShippedLineCall text eventWorkflowShippedText
run writeEventWorkflowShippedLineCall
ignoreOk writeEventWorkflowShippedLineCall Void
bindError writeEventWorkflowShippedLineError ConsoleWriteError writeEventWorkflowShippedLineCall
set lastConsoleWriteErrorCode writeEventWorkflowShippedLineError
branchIfError writeEventWorkflowShippedLineCall consoleWriteFailed

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label consoleWriteFailed
# rationale: lastConsoleWriteErrorCode holds whichever emit actually failed; its `set`
# ran immediately before the corresponding branchIfError, so the typed
# MainError.ConsoleWriteFailed value honestly names its cause (§12).
makeError consoleWriteFailure MainError.ConsoleWriteFailed lastConsoleWriteErrorCode
returnError consoleWriteFailure
