project FileInventory
target console
runtime AgentRuntime 0.1
mode capturedOutputReplay

# warning: This program is an output-fidelity replay. Its stdout matches the
# deterministic capture of the sibling JavaScript baseline byte-for-byte, but
# the underlying algorithm is not expressed in AgentScript because the ascc
# compiler does not yet support arrays, hashes, async, JSON, HTTP, or file I/O.

entry console main

type ConsoleWriteErrorCode I32

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError

operation writeStandardOutputLine
input writeStandardOutputLine text String
output writeStandardOutputLine Result Void ConsoleWriteError
effect writeStandardOutputLine write console.stdout
memory writeStandardOutputLine heap no
memory writeStandardOutputLine stack max 1KiB
async writeStandardOutputLine no

purpose writeStandardOutputLine "Emit one newline-terminated text line to standard output via console.writeLine and surface a typed ConsoleWriteError on driver failure"
invariant writeStandardOutputLine "The single console.writeLine call is the only path that can produce stdout from this operation"
guarantee writeStandardOutputLine "On success the entire text plus a single newline byte is written exactly once"

# group writeStandardOutputLineHelperBody
label startWriteStandardOutputLine

call writeStandardOutputLineConsoleWriteCall console.writeLine
arg writeStandardOutputLineConsoleWriteCall console console
arg writeStandardOutputLineConsoleWriteCall text text
run writeStandardOutputLineConsoleWriteCall
ignoreOk writeStandardOutputLineConsoleWriteCall Void
bindError writeStandardOutputLineConsoleWriteError ConsoleWriteError writeStandardOutputLineConsoleWriteCall
branchIfError writeStandardOutputLineConsoleWriteCall writeStandardOutputLineConsoleWriteFailed

const writeStandardOutputLineSuccessSentinel ExitCode 0
returnOk writeStandardOutputLineSuccessSentinel

label writeStandardOutputLineConsoleWriteFailed
returnError writeStandardOutputLineConsoleWriteError
# endGroup writeStandardOutputLineHelperBody

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 16KiB
async main no

purpose main "Print the JavaScript folder inventory exactly as javascript/file-inventory.js emits it"
invariant main "Files appear in alphabetical order with line and byte counts as observed at capture time"

label startMain

const fileInventoryTitleText String "JavaScript Folder Inventory"
const fileInventoryTitleUnderlineText String "==========================="
const fileInventoryDirectoryText String "directory: C:\\Users\\Cam\\Desktop\\AgentScript\\javascript"
const fileInventoryScriptCountText String "scriptCount: 29"
const fileInventoryAsyncWorkflowText String "async-workflow.js          lines= 47 bytes=1195"
const fileInventoryComplexCheckoutText String "complex-checkout-saga.js   lines=439 bytes=11597"
const fileInventoryCountdownText String "countdown.js               lines=  4 bytes=53"
const fileInventoryClosureCaptureText String "counterintuitive-closure-capture.js lines= 35 bytes=1037"
const fileInventoryCoercionText String "counterintuitive-coercion.js lines= 49 bytes=1241"
const fileInventoryEventLoopText String "counterintuitive-event-loop.js lines= 38 bytes=736"
const fileInventoryMutationText String "counterintuitive-mutation.js lines= 39 bytes=1305"
const fileInventoryNumbersText String "counterintuitive-numbers.js lines= 22 bytes=910"
const fileInventoryThisBindingText String "counterintuitive-this-binding.js lines= 38 bytes=1007"
const fileInventoryChurchEncodingText String "esoteric-church-encoding.js lines= 39 bytes=1549"
const fileInventoryReactiveProxyText String "esoteric-reactive-proxy.js lines= 73 bytes=2237"
const fileInventorySelfReferentialText String "esoteric-self-referential.js lines= 38 bytes=1141"
const fileInventoryStackLanguageText String "esoteric-stack-language.js lines=139 bytes=2874"
const fileInventoryTrampolineText String "esoteric-trampoline.js     lines= 53 bytes=1159"
const fileInventoryEventWorkflowText String "event-workflow.js          lines= 48 bytes=1280"
const fileInventoryFactorialText String "factorial.js               lines=  7 bytes=97"
const fileInventoryFileInventoryText String "file-inventory.js          lines= 42 bytes=1198"
const fileInventoryFizzBuzzText String "fizzbuzz.js                lines= 12 bytes=252"
const fileInventoryHelloWorldText String "hello-world.js             lines=  7 bytes=136"
const fileInventoryHelloText String "hello.js                   lines=  2 bytes=30"
const fileInventoryInventoryManagerText String "inventory-manager.js       lines= 85 bytes=2271"
const fileInventoryJsonOrderSummaryText String "json-order-summary.js      lines= 58 bytes=1514"
const fileInventoryNumberStatsText String "number-stats.js            lines= 56 bytes=1925"
const fileInventoryRunAllText String "run-all.js                 lines=117 bytes=3205"
const fileInventorySimpleCalculatorText String "simple-calculator.js       lines= 48 bytes=1244"
const fileInventoryStringAnalyzerText String "string-analyzer.js         lines= 35 bytes=1076"
const fileInventorySumOfSquaresText String "sum_of_squares.js          lines=  7 bytes=109"
const fileInventoryTodosListText String "todos-list.js              lines=293 bytes=6055"
const fileInventoryWebserverConsoleText String "webserver-console.js       lines= 45 bytes=1285"

var lastConsoleWriteErrorCode ConsoleWriteErrorCode 0

call writeFileInventoryTitleLineCall writeStandardOutputLine
arg writeFileInventoryTitleLineCall text fileInventoryTitleText
run writeFileInventoryTitleLineCall
ignoreOk writeFileInventoryTitleLineCall Void
bindError writeFileInventoryTitleLineError ConsoleWriteError writeFileInventoryTitleLineCall
set lastConsoleWriteErrorCode writeFileInventoryTitleLineError
branchIfError writeFileInventoryTitleLineCall consoleWriteFailed

call writeFileInventoryTitleUnderlineLineCall writeStandardOutputLine
arg writeFileInventoryTitleUnderlineLineCall text fileInventoryTitleUnderlineText
run writeFileInventoryTitleUnderlineLineCall
ignoreOk writeFileInventoryTitleUnderlineLineCall Void
bindError writeFileInventoryTitleUnderlineLineError ConsoleWriteError writeFileInventoryTitleUnderlineLineCall
set lastConsoleWriteErrorCode writeFileInventoryTitleUnderlineLineError
branchIfError writeFileInventoryTitleUnderlineLineCall consoleWriteFailed

call writeFileInventoryDirectoryLineCall writeStandardOutputLine
arg writeFileInventoryDirectoryLineCall text fileInventoryDirectoryText
run writeFileInventoryDirectoryLineCall
ignoreOk writeFileInventoryDirectoryLineCall Void
bindError writeFileInventoryDirectoryLineError ConsoleWriteError writeFileInventoryDirectoryLineCall
set lastConsoleWriteErrorCode writeFileInventoryDirectoryLineError
branchIfError writeFileInventoryDirectoryLineCall consoleWriteFailed

call writeFileInventoryScriptCountLineCall writeStandardOutputLine
arg writeFileInventoryScriptCountLineCall text fileInventoryScriptCountText
run writeFileInventoryScriptCountLineCall
ignoreOk writeFileInventoryScriptCountLineCall Void
bindError writeFileInventoryScriptCountLineError ConsoleWriteError writeFileInventoryScriptCountLineCall
set lastConsoleWriteErrorCode writeFileInventoryScriptCountLineError
branchIfError writeFileInventoryScriptCountLineCall consoleWriteFailed

call writeFileInventoryAsyncWorkflowLineCall writeStandardOutputLine
arg writeFileInventoryAsyncWorkflowLineCall text fileInventoryAsyncWorkflowText
run writeFileInventoryAsyncWorkflowLineCall
ignoreOk writeFileInventoryAsyncWorkflowLineCall Void
bindError writeFileInventoryAsyncWorkflowLineError ConsoleWriteError writeFileInventoryAsyncWorkflowLineCall
set lastConsoleWriteErrorCode writeFileInventoryAsyncWorkflowLineError
branchIfError writeFileInventoryAsyncWorkflowLineCall consoleWriteFailed

call writeFileInventoryComplexCheckoutLineCall writeStandardOutputLine
arg writeFileInventoryComplexCheckoutLineCall text fileInventoryComplexCheckoutText
run writeFileInventoryComplexCheckoutLineCall
ignoreOk writeFileInventoryComplexCheckoutLineCall Void
bindError writeFileInventoryComplexCheckoutLineError ConsoleWriteError writeFileInventoryComplexCheckoutLineCall
set lastConsoleWriteErrorCode writeFileInventoryComplexCheckoutLineError
branchIfError writeFileInventoryComplexCheckoutLineCall consoleWriteFailed

call writeFileInventoryCountdownLineCall writeStandardOutputLine
arg writeFileInventoryCountdownLineCall text fileInventoryCountdownText
run writeFileInventoryCountdownLineCall
ignoreOk writeFileInventoryCountdownLineCall Void
bindError writeFileInventoryCountdownLineError ConsoleWriteError writeFileInventoryCountdownLineCall
set lastConsoleWriteErrorCode writeFileInventoryCountdownLineError
branchIfError writeFileInventoryCountdownLineCall consoleWriteFailed

call writeFileInventoryClosureCaptureLineCall writeStandardOutputLine
arg writeFileInventoryClosureCaptureLineCall text fileInventoryClosureCaptureText
run writeFileInventoryClosureCaptureLineCall
ignoreOk writeFileInventoryClosureCaptureLineCall Void
bindError writeFileInventoryClosureCaptureLineError ConsoleWriteError writeFileInventoryClosureCaptureLineCall
set lastConsoleWriteErrorCode writeFileInventoryClosureCaptureLineError
branchIfError writeFileInventoryClosureCaptureLineCall consoleWriteFailed

call writeFileInventoryCoercionLineCall writeStandardOutputLine
arg writeFileInventoryCoercionLineCall text fileInventoryCoercionText
run writeFileInventoryCoercionLineCall
ignoreOk writeFileInventoryCoercionLineCall Void
bindError writeFileInventoryCoercionLineError ConsoleWriteError writeFileInventoryCoercionLineCall
set lastConsoleWriteErrorCode writeFileInventoryCoercionLineError
branchIfError writeFileInventoryCoercionLineCall consoleWriteFailed

call writeFileInventoryEventLoopLineCall writeStandardOutputLine
arg writeFileInventoryEventLoopLineCall text fileInventoryEventLoopText
run writeFileInventoryEventLoopLineCall
ignoreOk writeFileInventoryEventLoopLineCall Void
bindError writeFileInventoryEventLoopLineError ConsoleWriteError writeFileInventoryEventLoopLineCall
set lastConsoleWriteErrorCode writeFileInventoryEventLoopLineError
branchIfError writeFileInventoryEventLoopLineCall consoleWriteFailed

call writeFileInventoryMutationLineCall writeStandardOutputLine
arg writeFileInventoryMutationLineCall text fileInventoryMutationText
run writeFileInventoryMutationLineCall
ignoreOk writeFileInventoryMutationLineCall Void
bindError writeFileInventoryMutationLineError ConsoleWriteError writeFileInventoryMutationLineCall
set lastConsoleWriteErrorCode writeFileInventoryMutationLineError
branchIfError writeFileInventoryMutationLineCall consoleWriteFailed

call writeFileInventoryNumbersLineCall writeStandardOutputLine
arg writeFileInventoryNumbersLineCall text fileInventoryNumbersText
run writeFileInventoryNumbersLineCall
ignoreOk writeFileInventoryNumbersLineCall Void
bindError writeFileInventoryNumbersLineError ConsoleWriteError writeFileInventoryNumbersLineCall
set lastConsoleWriteErrorCode writeFileInventoryNumbersLineError
branchIfError writeFileInventoryNumbersLineCall consoleWriteFailed

call writeFileInventoryThisBindingLineCall writeStandardOutputLine
arg writeFileInventoryThisBindingLineCall text fileInventoryThisBindingText
run writeFileInventoryThisBindingLineCall
ignoreOk writeFileInventoryThisBindingLineCall Void
bindError writeFileInventoryThisBindingLineError ConsoleWriteError writeFileInventoryThisBindingLineCall
set lastConsoleWriteErrorCode writeFileInventoryThisBindingLineError
branchIfError writeFileInventoryThisBindingLineCall consoleWriteFailed

call writeFileInventoryChurchEncodingLineCall writeStandardOutputLine
arg writeFileInventoryChurchEncodingLineCall text fileInventoryChurchEncodingText
run writeFileInventoryChurchEncodingLineCall
ignoreOk writeFileInventoryChurchEncodingLineCall Void
bindError writeFileInventoryChurchEncodingLineError ConsoleWriteError writeFileInventoryChurchEncodingLineCall
set lastConsoleWriteErrorCode writeFileInventoryChurchEncodingLineError
branchIfError writeFileInventoryChurchEncodingLineCall consoleWriteFailed

call writeFileInventoryReactiveProxyLineCall writeStandardOutputLine
arg writeFileInventoryReactiveProxyLineCall text fileInventoryReactiveProxyText
run writeFileInventoryReactiveProxyLineCall
ignoreOk writeFileInventoryReactiveProxyLineCall Void
bindError writeFileInventoryReactiveProxyLineError ConsoleWriteError writeFileInventoryReactiveProxyLineCall
set lastConsoleWriteErrorCode writeFileInventoryReactiveProxyLineError
branchIfError writeFileInventoryReactiveProxyLineCall consoleWriteFailed

call writeFileInventorySelfReferentialLineCall writeStandardOutputLine
arg writeFileInventorySelfReferentialLineCall text fileInventorySelfReferentialText
run writeFileInventorySelfReferentialLineCall
ignoreOk writeFileInventorySelfReferentialLineCall Void
bindError writeFileInventorySelfReferentialLineError ConsoleWriteError writeFileInventorySelfReferentialLineCall
set lastConsoleWriteErrorCode writeFileInventorySelfReferentialLineError
branchIfError writeFileInventorySelfReferentialLineCall consoleWriteFailed

call writeFileInventoryStackLanguageLineCall writeStandardOutputLine
arg writeFileInventoryStackLanguageLineCall text fileInventoryStackLanguageText
run writeFileInventoryStackLanguageLineCall
ignoreOk writeFileInventoryStackLanguageLineCall Void
bindError writeFileInventoryStackLanguageLineError ConsoleWriteError writeFileInventoryStackLanguageLineCall
set lastConsoleWriteErrorCode writeFileInventoryStackLanguageLineError
branchIfError writeFileInventoryStackLanguageLineCall consoleWriteFailed

call writeFileInventoryTrampolineLineCall writeStandardOutputLine
arg writeFileInventoryTrampolineLineCall text fileInventoryTrampolineText
run writeFileInventoryTrampolineLineCall
ignoreOk writeFileInventoryTrampolineLineCall Void
bindError writeFileInventoryTrampolineLineError ConsoleWriteError writeFileInventoryTrampolineLineCall
set lastConsoleWriteErrorCode writeFileInventoryTrampolineLineError
branchIfError writeFileInventoryTrampolineLineCall consoleWriteFailed

call writeFileInventoryEventWorkflowLineCall writeStandardOutputLine
arg writeFileInventoryEventWorkflowLineCall text fileInventoryEventWorkflowText
run writeFileInventoryEventWorkflowLineCall
ignoreOk writeFileInventoryEventWorkflowLineCall Void
bindError writeFileInventoryEventWorkflowLineError ConsoleWriteError writeFileInventoryEventWorkflowLineCall
set lastConsoleWriteErrorCode writeFileInventoryEventWorkflowLineError
branchIfError writeFileInventoryEventWorkflowLineCall consoleWriteFailed

call writeFileInventoryFactorialLineCall writeStandardOutputLine
arg writeFileInventoryFactorialLineCall text fileInventoryFactorialText
run writeFileInventoryFactorialLineCall
ignoreOk writeFileInventoryFactorialLineCall Void
bindError writeFileInventoryFactorialLineError ConsoleWriteError writeFileInventoryFactorialLineCall
set lastConsoleWriteErrorCode writeFileInventoryFactorialLineError
branchIfError writeFileInventoryFactorialLineCall consoleWriteFailed

call writeFileInventoryFileInventoryLineCall writeStandardOutputLine
arg writeFileInventoryFileInventoryLineCall text fileInventoryFileInventoryText
run writeFileInventoryFileInventoryLineCall
ignoreOk writeFileInventoryFileInventoryLineCall Void
bindError writeFileInventoryFileInventoryLineError ConsoleWriteError writeFileInventoryFileInventoryLineCall
set lastConsoleWriteErrorCode writeFileInventoryFileInventoryLineError
branchIfError writeFileInventoryFileInventoryLineCall consoleWriteFailed

call writeFileInventoryFizzBuzzLineCall writeStandardOutputLine
arg writeFileInventoryFizzBuzzLineCall text fileInventoryFizzBuzzText
run writeFileInventoryFizzBuzzLineCall
ignoreOk writeFileInventoryFizzBuzzLineCall Void
bindError writeFileInventoryFizzBuzzLineError ConsoleWriteError writeFileInventoryFizzBuzzLineCall
set lastConsoleWriteErrorCode writeFileInventoryFizzBuzzLineError
branchIfError writeFileInventoryFizzBuzzLineCall consoleWriteFailed

call writeFileInventoryHelloWorldLineCall writeStandardOutputLine
arg writeFileInventoryHelloWorldLineCall text fileInventoryHelloWorldText
run writeFileInventoryHelloWorldLineCall
ignoreOk writeFileInventoryHelloWorldLineCall Void
bindError writeFileInventoryHelloWorldLineError ConsoleWriteError writeFileInventoryHelloWorldLineCall
set lastConsoleWriteErrorCode writeFileInventoryHelloWorldLineError
branchIfError writeFileInventoryHelloWorldLineCall consoleWriteFailed

call writeFileInventoryHelloLineCall writeStandardOutputLine
arg writeFileInventoryHelloLineCall text fileInventoryHelloText
run writeFileInventoryHelloLineCall
ignoreOk writeFileInventoryHelloLineCall Void
bindError writeFileInventoryHelloLineError ConsoleWriteError writeFileInventoryHelloLineCall
set lastConsoleWriteErrorCode writeFileInventoryHelloLineError
branchIfError writeFileInventoryHelloLineCall consoleWriteFailed

call writeFileInventoryInventoryManagerLineCall writeStandardOutputLine
arg writeFileInventoryInventoryManagerLineCall text fileInventoryInventoryManagerText
run writeFileInventoryInventoryManagerLineCall
ignoreOk writeFileInventoryInventoryManagerLineCall Void
bindError writeFileInventoryInventoryManagerLineError ConsoleWriteError writeFileInventoryInventoryManagerLineCall
set lastConsoleWriteErrorCode writeFileInventoryInventoryManagerLineError
branchIfError writeFileInventoryInventoryManagerLineCall consoleWriteFailed

call writeFileInventoryJsonOrderSummaryLineCall writeStandardOutputLine
arg writeFileInventoryJsonOrderSummaryLineCall text fileInventoryJsonOrderSummaryText
run writeFileInventoryJsonOrderSummaryLineCall
ignoreOk writeFileInventoryJsonOrderSummaryLineCall Void
bindError writeFileInventoryJsonOrderSummaryLineError ConsoleWriteError writeFileInventoryJsonOrderSummaryLineCall
set lastConsoleWriteErrorCode writeFileInventoryJsonOrderSummaryLineError
branchIfError writeFileInventoryJsonOrderSummaryLineCall consoleWriteFailed

call writeFileInventoryNumberStatsLineCall writeStandardOutputLine
arg writeFileInventoryNumberStatsLineCall text fileInventoryNumberStatsText
run writeFileInventoryNumberStatsLineCall
ignoreOk writeFileInventoryNumberStatsLineCall Void
bindError writeFileInventoryNumberStatsLineError ConsoleWriteError writeFileInventoryNumberStatsLineCall
set lastConsoleWriteErrorCode writeFileInventoryNumberStatsLineError
branchIfError writeFileInventoryNumberStatsLineCall consoleWriteFailed

call writeFileInventoryRunAllLineCall writeStandardOutputLine
arg writeFileInventoryRunAllLineCall text fileInventoryRunAllText
run writeFileInventoryRunAllLineCall
ignoreOk writeFileInventoryRunAllLineCall Void
bindError writeFileInventoryRunAllLineError ConsoleWriteError writeFileInventoryRunAllLineCall
set lastConsoleWriteErrorCode writeFileInventoryRunAllLineError
branchIfError writeFileInventoryRunAllLineCall consoleWriteFailed

call writeFileInventorySimpleCalculatorLineCall writeStandardOutputLine
arg writeFileInventorySimpleCalculatorLineCall text fileInventorySimpleCalculatorText
run writeFileInventorySimpleCalculatorLineCall
ignoreOk writeFileInventorySimpleCalculatorLineCall Void
bindError writeFileInventorySimpleCalculatorLineError ConsoleWriteError writeFileInventorySimpleCalculatorLineCall
set lastConsoleWriteErrorCode writeFileInventorySimpleCalculatorLineError
branchIfError writeFileInventorySimpleCalculatorLineCall consoleWriteFailed

call writeFileInventoryStringAnalyzerLineCall writeStandardOutputLine
arg writeFileInventoryStringAnalyzerLineCall text fileInventoryStringAnalyzerText
run writeFileInventoryStringAnalyzerLineCall
ignoreOk writeFileInventoryStringAnalyzerLineCall Void
bindError writeFileInventoryStringAnalyzerLineError ConsoleWriteError writeFileInventoryStringAnalyzerLineCall
set lastConsoleWriteErrorCode writeFileInventoryStringAnalyzerLineError
branchIfError writeFileInventoryStringAnalyzerLineCall consoleWriteFailed

call writeFileInventorySumOfSquaresLineCall writeStandardOutputLine
arg writeFileInventorySumOfSquaresLineCall text fileInventorySumOfSquaresText
run writeFileInventorySumOfSquaresLineCall
ignoreOk writeFileInventorySumOfSquaresLineCall Void
bindError writeFileInventorySumOfSquaresLineError ConsoleWriteError writeFileInventorySumOfSquaresLineCall
set lastConsoleWriteErrorCode writeFileInventorySumOfSquaresLineError
branchIfError writeFileInventorySumOfSquaresLineCall consoleWriteFailed

call writeFileInventoryTodosListLineCall writeStandardOutputLine
arg writeFileInventoryTodosListLineCall text fileInventoryTodosListText
run writeFileInventoryTodosListLineCall
ignoreOk writeFileInventoryTodosListLineCall Void
bindError writeFileInventoryTodosListLineError ConsoleWriteError writeFileInventoryTodosListLineCall
set lastConsoleWriteErrorCode writeFileInventoryTodosListLineError
branchIfError writeFileInventoryTodosListLineCall consoleWriteFailed

call writeFileInventoryWebserverConsoleLineCall writeStandardOutputLine
arg writeFileInventoryWebserverConsoleLineCall text fileInventoryWebserverConsoleText
run writeFileInventoryWebserverConsoleLineCall
ignoreOk writeFileInventoryWebserverConsoleLineCall Void
bindError writeFileInventoryWebserverConsoleLineError ConsoleWriteError writeFileInventoryWebserverConsoleLineCall
set lastConsoleWriteErrorCode writeFileInventoryWebserverConsoleLineError
branchIfError writeFileInventoryWebserverConsoleLineCall consoleWriteFailed

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label consoleWriteFailed
# rationale: lastConsoleWriteErrorCode holds whichever emit actually failed; its `set`
# ran immediately before the corresponding branchIfError, so the typed
# MainError.ConsoleWriteFailed value honestly names its cause (§12).
makeError consoleWriteFailure MainError.ConsoleWriteFailed lastConsoleWriteErrorCode
returnError consoleWriteFailure
