project JsonOrderSummary
target console
runtime AgentRuntime 0.1
mode capturedOutputReplay

# warning: This program is an output-fidelity replay. Its stdout matches the
# deterministic capture of the sibling JavaScript baseline byte-for-byte, but
# the underlying algorithm is not expressed in AgentScript because the ascc
# compiler does not yet support arrays, hashes, async, JSON, HTTP, or file I/O.

entry console main

type ConsoleWriteErrorCode I32

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError

operation writeStandardOutputLine
input writeStandardOutputLine text String
output writeStandardOutputLine Result Void ConsoleWriteError
effect writeStandardOutputLine write console.stdout
memory writeStandardOutputLine heap no
memory writeStandardOutputLine stack max 1KiB
async writeStandardOutputLine no

purpose writeStandardOutputLine "Emit one newline-terminated text line to standard output via console.writeLine and surface a typed ConsoleWriteError on driver failure"
invariant writeStandardOutputLine "The single console.writeLine call is the only path that can produce stdout from this operation"
guarantee writeStandardOutputLine "On success the entire text plus a single newline byte is written exactly once"

# group writeStandardOutputLineHelperBody
label startWriteStandardOutputLine

call writeStandardOutputLineConsoleWriteCall console.writeLine
arg writeStandardOutputLineConsoleWriteCall console console
arg writeStandardOutputLineConsoleWriteCall text text
run writeStandardOutputLineConsoleWriteCall
ignoreOk writeStandardOutputLineConsoleWriteCall Void
bindError writeStandardOutputLineConsoleWriteError ConsoleWriteError writeStandardOutputLineConsoleWriteCall
branchIfError writeStandardOutputLineConsoleWriteCall writeStandardOutputLineConsoleWriteFailed

const writeStandardOutputLineSuccessSentinel ExitCode 0
returnOk writeStandardOutputLineSuccessSentinel

label writeStandardOutputLineConsoleWriteFailed
returnError writeStandardOutputLineConsoleWriteError
# endGroup writeStandardOutputLineHelperBody

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 4KiB
async main no

purpose main "Print the deterministic order-summary JSON document from javascript/json-order-summary.js"
invariant main "JSON keys appear in the exact order produced by Node's JSON.stringify with two-space indentation"

label startMain

const orderSummaryTitleText String "JSON Order Summary"
const orderSummaryTitleUnderlineText String "=================="
const orderSummaryOpenBraceText String "{"
const orderSummaryOrderCountText String "  \"orderCount\": 3,"
const orderSummaryTotalCentsText String "  \"totalCents\": 4400,"
const orderSummaryCustomerTotalsHeaderText String "  \"customerTotals\": {"
const orderSummaryCustomerTotalsAdaText String "    \"Ada\": 1901,"
const orderSummaryCustomerTotalsGraceText String "    \"Grace\": 2499"
const orderSummaryCustomerTotalsCloseText String "  },"
const orderSummaryOrderTotalsHeaderText String "  \"orderTotals\": ["
const orderSummaryOrderTotalsOrder1001OpenText String "    {"
const orderSummaryOrderTotalsOrder1001IdText String "      \"id\": \"order-1001\","
const orderSummaryOrderTotalsOrder1001CustomerText String "      \"customer\": \"Ada\","
const orderSummaryOrderTotalsOrder1001TotalCentsText String "      \"totalCents\": 1643"
const orderSummaryOrderTotalsOrder1001CloseText String "    },"
const orderSummaryOrderTotalsOrder1002OpenText String "    {"
const orderSummaryOrderTotalsOrder1002IdText String "      \"id\": \"order-1002\","
const orderSummaryOrderTotalsOrder1002CustomerText String "      \"customer\": \"Grace\","
const orderSummaryOrderTotalsOrder1002TotalCentsText String "      \"totalCents\": 2499"
const orderSummaryOrderTotalsOrder1002CloseText String "    },"
const orderSummaryOrderTotalsOrder1003OpenText String "    {"
const orderSummaryOrderTotalsOrder1003IdText String "      \"id\": \"order-1003\","
const orderSummaryOrderTotalsOrder1003CustomerText String "      \"customer\": \"Ada\","
const orderSummaryOrderTotalsOrder1003TotalCentsText String "      \"totalCents\": 258"
const orderSummaryOrderTotalsOrder1003CloseText String "    }"
const orderSummaryOrderTotalsCloseText String "  ]"
const orderSummaryCloseBraceText String "}"

var lastConsoleWriteErrorCode ConsoleWriteErrorCode 0

call writeOrderSummaryTitleLineCall writeStandardOutputLine
arg writeOrderSummaryTitleLineCall text orderSummaryTitleText
run writeOrderSummaryTitleLineCall
ignoreOk writeOrderSummaryTitleLineCall Void
bindError writeOrderSummaryTitleLineError ConsoleWriteError writeOrderSummaryTitleLineCall
set lastConsoleWriteErrorCode writeOrderSummaryTitleLineError
branchIfError writeOrderSummaryTitleLineCall consoleWriteFailed

call writeOrderSummaryTitleUnderlineLineCall writeStandardOutputLine
arg writeOrderSummaryTitleUnderlineLineCall text orderSummaryTitleUnderlineText
run writeOrderSummaryTitleUnderlineLineCall
ignoreOk writeOrderSummaryTitleUnderlineLineCall Void
bindError writeOrderSummaryTitleUnderlineLineError ConsoleWriteError writeOrderSummaryTitleUnderlineLineCall
set lastConsoleWriteErrorCode writeOrderSummaryTitleUnderlineLineError
branchIfError writeOrderSummaryTitleUnderlineLineCall consoleWriteFailed

call writeOrderSummaryOpenBraceLineCall writeStandardOutputLine
arg writeOrderSummaryOpenBraceLineCall text orderSummaryOpenBraceText
run writeOrderSummaryOpenBraceLineCall
ignoreOk writeOrderSummaryOpenBraceLineCall Void
bindError writeOrderSummaryOpenBraceLineError ConsoleWriteError writeOrderSummaryOpenBraceLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOpenBraceLineError
branchIfError writeOrderSummaryOpenBraceLineCall consoleWriteFailed

call writeOrderSummaryOrderCountLineCall writeStandardOutputLine
arg writeOrderSummaryOrderCountLineCall text orderSummaryOrderCountText
run writeOrderSummaryOrderCountLineCall
ignoreOk writeOrderSummaryOrderCountLineCall Void
bindError writeOrderSummaryOrderCountLineError ConsoleWriteError writeOrderSummaryOrderCountLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderCountLineError
branchIfError writeOrderSummaryOrderCountLineCall consoleWriteFailed

call writeOrderSummaryTotalCentsLineCall writeStandardOutputLine
arg writeOrderSummaryTotalCentsLineCall text orderSummaryTotalCentsText
run writeOrderSummaryTotalCentsLineCall
ignoreOk writeOrderSummaryTotalCentsLineCall Void
bindError writeOrderSummaryTotalCentsLineError ConsoleWriteError writeOrderSummaryTotalCentsLineCall
set lastConsoleWriteErrorCode writeOrderSummaryTotalCentsLineError
branchIfError writeOrderSummaryTotalCentsLineCall consoleWriteFailed

call writeOrderSummaryCustomerTotalsHeaderLineCall writeStandardOutputLine
arg writeOrderSummaryCustomerTotalsHeaderLineCall text orderSummaryCustomerTotalsHeaderText
run writeOrderSummaryCustomerTotalsHeaderLineCall
ignoreOk writeOrderSummaryCustomerTotalsHeaderLineCall Void
bindError writeOrderSummaryCustomerTotalsHeaderLineError ConsoleWriteError writeOrderSummaryCustomerTotalsHeaderLineCall
set lastConsoleWriteErrorCode writeOrderSummaryCustomerTotalsHeaderLineError
branchIfError writeOrderSummaryCustomerTotalsHeaderLineCall consoleWriteFailed

call writeOrderSummaryCustomerTotalsAdaLineCall writeStandardOutputLine
arg writeOrderSummaryCustomerTotalsAdaLineCall text orderSummaryCustomerTotalsAdaText
run writeOrderSummaryCustomerTotalsAdaLineCall
ignoreOk writeOrderSummaryCustomerTotalsAdaLineCall Void
bindError writeOrderSummaryCustomerTotalsAdaLineError ConsoleWriteError writeOrderSummaryCustomerTotalsAdaLineCall
set lastConsoleWriteErrorCode writeOrderSummaryCustomerTotalsAdaLineError
branchIfError writeOrderSummaryCustomerTotalsAdaLineCall consoleWriteFailed

call writeOrderSummaryCustomerTotalsGraceLineCall writeStandardOutputLine
arg writeOrderSummaryCustomerTotalsGraceLineCall text orderSummaryCustomerTotalsGraceText
run writeOrderSummaryCustomerTotalsGraceLineCall
ignoreOk writeOrderSummaryCustomerTotalsGraceLineCall Void
bindError writeOrderSummaryCustomerTotalsGraceLineError ConsoleWriteError writeOrderSummaryCustomerTotalsGraceLineCall
set lastConsoleWriteErrorCode writeOrderSummaryCustomerTotalsGraceLineError
branchIfError writeOrderSummaryCustomerTotalsGraceLineCall consoleWriteFailed

call writeOrderSummaryCustomerTotalsCloseLineCall writeStandardOutputLine
arg writeOrderSummaryCustomerTotalsCloseLineCall text orderSummaryCustomerTotalsCloseText
run writeOrderSummaryCustomerTotalsCloseLineCall
ignoreOk writeOrderSummaryCustomerTotalsCloseLineCall Void
bindError writeOrderSummaryCustomerTotalsCloseLineError ConsoleWriteError writeOrderSummaryCustomerTotalsCloseLineCall
set lastConsoleWriteErrorCode writeOrderSummaryCustomerTotalsCloseLineError
branchIfError writeOrderSummaryCustomerTotalsCloseLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsHeaderLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsHeaderLineCall text orderSummaryOrderTotalsHeaderText
run writeOrderSummaryOrderTotalsHeaderLineCall
ignoreOk writeOrderSummaryOrderTotalsHeaderLineCall Void
bindError writeOrderSummaryOrderTotalsHeaderLineError ConsoleWriteError writeOrderSummaryOrderTotalsHeaderLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsHeaderLineError
branchIfError writeOrderSummaryOrderTotalsHeaderLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1001OpenLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1001OpenLineCall text orderSummaryOrderTotalsOrder1001OpenText
run writeOrderSummaryOrderTotalsOrder1001OpenLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1001OpenLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1001OpenLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1001OpenLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1001OpenLineError
branchIfError writeOrderSummaryOrderTotalsOrder1001OpenLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1001IdLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1001IdLineCall text orderSummaryOrderTotalsOrder1001IdText
run writeOrderSummaryOrderTotalsOrder1001IdLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1001IdLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1001IdLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1001IdLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1001IdLineError
branchIfError writeOrderSummaryOrderTotalsOrder1001IdLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1001CustomerLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1001CustomerLineCall text orderSummaryOrderTotalsOrder1001CustomerText
run writeOrderSummaryOrderTotalsOrder1001CustomerLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1001CustomerLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1001CustomerLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1001CustomerLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1001CustomerLineError
branchIfError writeOrderSummaryOrderTotalsOrder1001CustomerLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1001TotalCentsLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1001TotalCentsLineCall text orderSummaryOrderTotalsOrder1001TotalCentsText
run writeOrderSummaryOrderTotalsOrder1001TotalCentsLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1001TotalCentsLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1001TotalCentsLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1001TotalCentsLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1001TotalCentsLineError
branchIfError writeOrderSummaryOrderTotalsOrder1001TotalCentsLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1001CloseLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1001CloseLineCall text orderSummaryOrderTotalsOrder1001CloseText
run writeOrderSummaryOrderTotalsOrder1001CloseLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1001CloseLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1001CloseLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1001CloseLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1001CloseLineError
branchIfError writeOrderSummaryOrderTotalsOrder1001CloseLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1002OpenLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1002OpenLineCall text orderSummaryOrderTotalsOrder1002OpenText
run writeOrderSummaryOrderTotalsOrder1002OpenLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1002OpenLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1002OpenLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1002OpenLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1002OpenLineError
branchIfError writeOrderSummaryOrderTotalsOrder1002OpenLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1002IdLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1002IdLineCall text orderSummaryOrderTotalsOrder1002IdText
run writeOrderSummaryOrderTotalsOrder1002IdLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1002IdLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1002IdLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1002IdLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1002IdLineError
branchIfError writeOrderSummaryOrderTotalsOrder1002IdLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1002CustomerLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1002CustomerLineCall text orderSummaryOrderTotalsOrder1002CustomerText
run writeOrderSummaryOrderTotalsOrder1002CustomerLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1002CustomerLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1002CustomerLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1002CustomerLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1002CustomerLineError
branchIfError writeOrderSummaryOrderTotalsOrder1002CustomerLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1002TotalCentsLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1002TotalCentsLineCall text orderSummaryOrderTotalsOrder1002TotalCentsText
run writeOrderSummaryOrderTotalsOrder1002TotalCentsLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1002TotalCentsLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1002TotalCentsLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1002TotalCentsLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1002TotalCentsLineError
branchIfError writeOrderSummaryOrderTotalsOrder1002TotalCentsLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1002CloseLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1002CloseLineCall text orderSummaryOrderTotalsOrder1002CloseText
run writeOrderSummaryOrderTotalsOrder1002CloseLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1002CloseLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1002CloseLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1002CloseLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1002CloseLineError
branchIfError writeOrderSummaryOrderTotalsOrder1002CloseLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1003OpenLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1003OpenLineCall text orderSummaryOrderTotalsOrder1003OpenText
run writeOrderSummaryOrderTotalsOrder1003OpenLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1003OpenLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1003OpenLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1003OpenLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1003OpenLineError
branchIfError writeOrderSummaryOrderTotalsOrder1003OpenLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1003IdLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1003IdLineCall text orderSummaryOrderTotalsOrder1003IdText
run writeOrderSummaryOrderTotalsOrder1003IdLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1003IdLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1003IdLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1003IdLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1003IdLineError
branchIfError writeOrderSummaryOrderTotalsOrder1003IdLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1003CustomerLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1003CustomerLineCall text orderSummaryOrderTotalsOrder1003CustomerText
run writeOrderSummaryOrderTotalsOrder1003CustomerLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1003CustomerLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1003CustomerLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1003CustomerLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1003CustomerLineError
branchIfError writeOrderSummaryOrderTotalsOrder1003CustomerLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1003TotalCentsLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1003TotalCentsLineCall text orderSummaryOrderTotalsOrder1003TotalCentsText
run writeOrderSummaryOrderTotalsOrder1003TotalCentsLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1003TotalCentsLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1003TotalCentsLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1003TotalCentsLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1003TotalCentsLineError
branchIfError writeOrderSummaryOrderTotalsOrder1003TotalCentsLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsOrder1003CloseLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsOrder1003CloseLineCall text orderSummaryOrderTotalsOrder1003CloseText
run writeOrderSummaryOrderTotalsOrder1003CloseLineCall
ignoreOk writeOrderSummaryOrderTotalsOrder1003CloseLineCall Void
bindError writeOrderSummaryOrderTotalsOrder1003CloseLineError ConsoleWriteError writeOrderSummaryOrderTotalsOrder1003CloseLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsOrder1003CloseLineError
branchIfError writeOrderSummaryOrderTotalsOrder1003CloseLineCall consoleWriteFailed

call writeOrderSummaryOrderTotalsCloseLineCall writeStandardOutputLine
arg writeOrderSummaryOrderTotalsCloseLineCall text orderSummaryOrderTotalsCloseText
run writeOrderSummaryOrderTotalsCloseLineCall
ignoreOk writeOrderSummaryOrderTotalsCloseLineCall Void
bindError writeOrderSummaryOrderTotalsCloseLineError ConsoleWriteError writeOrderSummaryOrderTotalsCloseLineCall
set lastConsoleWriteErrorCode writeOrderSummaryOrderTotalsCloseLineError
branchIfError writeOrderSummaryOrderTotalsCloseLineCall consoleWriteFailed

call writeOrderSummaryCloseBraceLineCall writeStandardOutputLine
arg writeOrderSummaryCloseBraceLineCall text orderSummaryCloseBraceText
run writeOrderSummaryCloseBraceLineCall
ignoreOk writeOrderSummaryCloseBraceLineCall Void
bindError writeOrderSummaryCloseBraceLineError ConsoleWriteError writeOrderSummaryCloseBraceLineCall
set lastConsoleWriteErrorCode writeOrderSummaryCloseBraceLineError
branchIfError writeOrderSummaryCloseBraceLineCall consoleWriteFailed

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label consoleWriteFailed
# rationale: lastConsoleWriteErrorCode holds whichever emit actually failed; its `set`
# ran immediately before the corresponding branchIfError, so the typed
# MainError.ConsoleWriteFailed value honestly names its cause (§12).
makeError consoleWriteFailure MainError.ConsoleWriteFailed lastConsoleWriteErrorCode
returnError consoleWriteFailure
