project Factorial
target console
runtime AgentRuntime 0.1

entry console main

type FactorialCounter I64
type FactorialAccumulator I64
type PositiveFactorialStep I64

error MainError
errorCase MainError ConsoleWriteFailed ConsoleWriteError
errorCase MainError FactorialUpperLimitTooLarge
errorCase MainError FactorialAccumulatorOverflowed FactorialOverflowError

operation main
input main console Console
output main Result ExitCode MainError
effect main write console.stdout
memory main heap no
memory main stack max 16KiB
async main no

purpose main "Compute the factorial of factorialUpperLimit and print the result as a single line"
invariant main "At factorialLoopHead, currentFactorialAccumulator equals factorial(currentFactorialCounter - 1)"
invariant main "factorialUpperLimit must be less than or equal to factorialOverflowSafeUpperLimit before the loop runs"
invariant main "factorialStepValue is strictly greater than zero"

label startMain

const factorialLowerLimit FactorialCounter 1
const factorialUpperLimit FactorialCounter 10
const factorialOverflowSafeUpperLimit FactorialCounter 20
const factorialStepValue PositiveFactorialStep 1
const factorialAccumulatorInitial FactorialAccumulator 1

var currentFactorialCounter FactorialCounter factorialLowerLimit
var currentFactorialAccumulator FactorialAccumulator factorialAccumulatorInitial

# rationale: Confirm factorialUpperLimit stays inside the range where I64 factorial accumulation is provably safe.
# The largest factorialUpperLimit whose factorial fits in a signed 64-bit integer is twenty, so any request
# beyond that must be rejected with a typed MainError variant rather than silently overflowing.
call factorialUpperLimitSafetyCheckCall FactorialCounter.lessThanOrEqual
arg factorialUpperLimitSafetyCheckCall left factorialUpperLimit
arg factorialUpperLimitSafetyCheckCall right factorialOverflowSafeUpperLimit
run factorialUpperLimitSafetyCheckCall
bind factorialUpperLimitIsOverflowSafe Bool factorialUpperLimitSafetyCheckCall

branchIf factorialUpperLimitIsOverflowSafe factorialLoopHead
branch factorialUpperLimitRejected

label factorialLoopHead

# rationale: Continue while currentFactorialCounter is less than or equal to factorialUpperLimit.
call factorialRangeCheckCall FactorialCounter.lessThanOrEqual
arg factorialRangeCheckCall left currentFactorialCounter
arg factorialRangeCheckCall right factorialUpperLimit
run factorialRangeCheckCall
bind factorialShouldContinue Bool factorialRangeCheckCall

branchIf factorialShouldContinue factorialLoopBody
branch factorialFinished

label factorialLoopBody

# rationale: Multiply currentFactorialAccumulator by currentFactorialCounter using checked arithmetic.
# A successful multiplication binds the new accumulator value; an overflow takes the failure leg and
# surfaces a typed FactorialOverflowError through MainError.FactorialAccumulatorOverflowed.
call factorialAccumulatorMultiplyCall FactorialAccumulator.checkedMultiplyByCounter
arg factorialAccumulatorMultiplyCall accumulator currentFactorialAccumulator
arg factorialAccumulatorMultiplyCall counter currentFactorialCounter
run factorialAccumulatorMultiplyCall
bindOk nextFactorialAccumulator FactorialAccumulator factorialAccumulatorMultiplyCall
bindError factorialAccumulatorOverflowError FactorialOverflowError factorialAccumulatorMultiplyCall
branchIfError factorialAccumulatorMultiplyCall factorialAccumulatorOverflowed

set currentFactorialAccumulator nextFactorialAccumulator

# rationale: Advance the counter by exactly factorialStepValue; the typed PositiveFactorialStep guarantees forward progress.
call factorialCounterIncrementCall FactorialCounter.addPositiveStep
arg factorialCounterIncrementCall counter currentFactorialCounter
arg factorialCounterIncrementCall step factorialStepValue
run factorialCounterIncrementCall
bind nextFactorialCounter FactorialCounter factorialCounterIncrementCall

set currentFactorialCounter nextFactorialCounter
branch factorialLoopHead

label factorialFinished

# rationale: Emit the final accumulator as a single line of standard output.
call writeFinalFactorialAccumulatorCall console.writeIntegerLine
arg writeFinalFactorialAccumulatorCall console console
arg writeFinalFactorialAccumulatorCall value currentFactorialAccumulator
run writeFinalFactorialAccumulatorCall
ignoreOk writeFinalFactorialAccumulatorCall Void
bindError writeFinalFactorialAccumulatorError ConsoleWriteError writeFinalFactorialAccumulatorCall
branchIfError writeFinalFactorialAccumulatorCall consoleWriteFailed

const successfulExitCode ExitCode 0
returnOk successfulExitCode

label factorialUpperLimitRejected
# failure: The configured factorialUpperLimit exceeds the I64 overflow-safe limit; reject before any multiplication runs.
makeError factorialUpperLimitRejectedFailure MainError.FactorialUpperLimitTooLarge
returnError factorialUpperLimitRejectedFailure

label factorialAccumulatorOverflowed
# failure: The checked multiplication reported overflow; carry the raw FactorialOverflowError through the typed MainError.
makeError factorialAccumulatorOverflowFailure MainError.FactorialAccumulatorOverflowed factorialAccumulatorOverflowError
returnError factorialAccumulatorOverflowFailure

label consoleWriteFailed
# failure: The console write failed after the factorial value was already computed; surface as MainError.ConsoleWriteFailed.
makeError consoleWriteFailure MainError.ConsoleWriteFailed writeFinalFactorialAccumulatorError
returnError consoleWriteFailure
